### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by akhilprogrammer** [Hexer10/youtube_explode_dart#10]

**Comment by akhilprogrammer** [comment]
Because every version of flutter_test from sdk depends on xml 3.5.0 and youtube_explode_dart >=0.0.6 depends on xml ^3.7.0, flutter_test from sdk is incompatible with youtube_explode_dart >=0.0.6.

**Comment by Hexer10** [comment]
Should be fixed with https://github.com/Hexer10/youtube_explode_dart/pull/12

**Comment by Hexer10** [comment]
Published in version [0.0.8](https://pub.dev/packages/youtube_explode_dart/versions/0.0.8)

**Comment by akhilprogrammer** [comment]
wow...
