### ISSUE TITLE
[BUG] 404 Not found error is occurred. Youtube may change something. 

### ISSUE THREAD

**Issue by desunny** [Hexer10/youtube_explode_dart#104]
Here is error log. The library version number I used is 'youtube_explode_dart: ^1.7.5'. Please check below. Thanks in advance. 

E/flutter ( 9967): [ERROR:flutter/lib/ui/ui_dart_state.cc(184)] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
E/flutter ( 9967): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
E/flutter ( 9967): If this issue persists, please report it on the project's GitHub page.
E/flutter ( 9967): Request: GET https://youtube.com/list_ajax?style=json&action_get_list=1&list=PLb8NUYaYc3RmXcZ94POhxzvgEjop0j-mk&index=0&hl=en
E/flutter ( 9967): Response: (404)
E/flutter ( 9967): 
E/flutter ( 9967): #0      YoutubeHttpClient._validateResponse (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:47:7)
E/flutter ( 9967): #1      YoutubeHttpClient.getString (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:57:7)
E/flutter ( 9967): <asynchronous suspension>
E/flutter ( 9967): #2      PlaylistResponse.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/responses/playlist_response.dart:58:17)
E/flutter ( 9967): <asynchronous suspension>
E/flutter ( 9967): #3      retry (package:youtube_explode_dart/src/retry.dart:15:14)
E/flutter ( 9967): <asynchronous suspension>
E/flutter ( 9967): #4      PlaylistClient.getVideos (package:youtube_explode_dart/src/playlists/playlist_client.dart:39:11)
E/flutter ( 9967): <asynchronous suspension>
E/flutter ( 9967): #5      Stream.toList.<anonymous closure> (dart:async/stream.dart)
E/flutter ( 9967): <asynchronous suspension>
E/flutter ( 9967): 
W/ple.mind_app_y( 9967): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)

**Comment by MassimoTambu** [comment]
In my case, updating to `^1.8.0-beta.5` version solved this issue.

**Comment by desunny** [comment]
> In my case, updating to `^1.8.0-beta.5` version solved this issue.

Thank you. I solved it. Thanks to you again.
