### ISSUE TITLE
[BUG] #102 issue still haven't merge into master yet

### ISSUE THREAD

**Issue by minhthong095** [Hexer10/youtube_explode_dart#106]
I checked this [commit log](https://github.com/Hexer10/youtube_explode_dart/commit/13249aed18510ae576d5f0b9ea1207ec11fe3e47) and see log changes in youtube_explode_dart/lib/src/videos/streams/streams_client.dart file in master branch but don't see any changes relate to fix #102.

**Comment by Hexer10** [comment]
They were merged in the beta version now `1.8.0` and those fixes should be implemented.
