### ISSUE TITLE
Implements Null-Safety

### ISSUE THREAD

**Issue by MassimoTambu** [Hexer10/youtube_explode_dart#107]
Hi!
Did you have any plans for a null-safety version?

**Comment by Hexer10** [comment]
This is already on my todo list thanks for creating an issue, I cannot give a proper timeline but I should be able to migrate the project to nnbd in the coming week(s)

**Comment by Hexer10** [comment]
This took less than I expected, I've already pushed a new version `1.9.0-nullsafety.2` which introduces support to nnbd.
It should work without any major breaking changes, if you have time to test it out it would be awesome to get some feedback.

**Comment by MassimoTambu** [comment]
Great, I'll check it the next days.

**Comment by MassimoTambu** [comment]
Okay, at the moment I checked if it gets the manifest, the audio and video qualities and the stream download. Everything worked.

**Comment by Hexer10** [comment]
I decided to make it to stable, you can update to `1.9.0` now
