### ISSUE TITLE
[RequestLimitExceededException]

### ISSUE THREAD

**Issue by Twapa** [Hexer10/youtube_explode_dart#111]
**RequestLimitExceededException**
Exception has occurred.
RequestLimitExceededException (RequestLimitExceededException: Failed to perform an HTTP request to YouTube because of rate limiting.
This error indicates that YouTube thinks there were too many requests made from this IP and considers it suspicious.
To resolve this error, please wait some time and try again -or- try injecting an HttpClient that has cookies for an authenticated user.
Unfortunately, there's nothing the library can do to work around this error.
Request: GET https://youtube.com/get_video_info?video_id=9()l=embedded&eurl=https://youtube.googleapis.com/v/5c9GG5mPizQ&hl=en
Response: Instance of 'Response'
)

what trick can be used here ?**

**Comment by Artx-II** [comment]
This shouldn't be a bug, like the exception thrown says, there is nothing the library can do by itself. I will tell you the steps I do to fix this issue that might be able to give you an idea of what to do:

1- Create a new custom HttpClient
2- Retrieve the GET request url from the Exception
3- Open a new Route/Dialog which uses a WebView widget with initial url equal to the url retrieved
4- This will open the youtube captcha verification, solve the captcha and then retrieve the cookies with CookieManager
5- Add to your custom HttpClient the cookies retrieved from the CookieManager
6- Run the function again and it will now work

I would recommend saving the cookies and then give them to your custom HttpClient client when you initialize it, sharedPrefences would come very useful for that, that way you will get the RequestLimitExceededException much less frequently.

**Comment by Hexer10** [comment]
Thanks to @Artx-II for the nice explanation, closing this.
