### ISSUE TITLE
Implement Subtitles/CC filter for video search.

### ISSUE THREAD

**Issue by tuanbs** [Hexer10/youtube_explode_dart#112]
Hi, thanks for this useful plugin. Can you please tell me if there's anyway I can get the searched videos that have closed caption (CC) only? I tried and able to get the searched videos but there's no option to filer videos with CC only. When I use YouTube API, it has the option `'videoCaption': 'closedCaption'`, then it returns the list of videos that have CC only. Is it possible to achieve the same thing with this plugin? If not, hope this feature can be implemented in the future version. And please keep evolving this plugin because you guys are doing an awesome job. Thanks you very much.

**Comment by Hexer10** [comment]
This is not possible currently and I'm not sure this can even be implemented, directly in the library  since youtube doesn't expose that kind of reach in the search page. The filter that could be implemented are one of these ![filter list](https://imgur.com/3g64OH9) 


The only way I think this would be doable is to manually check for each video if the closed captions are available

**Comment by tuanbs** [comment]
> This is not possible currently and I'm not sure this can even be implemented, directly in the library since youtube doesn't expose that kind of reach in the search page. The filter that could be implemented are one of these ![filter list](https://camo.githubusercontent.com/9b99de3255a8949720abd18c4b61db7323e3ad0d61dec29d83b5f482b5162dc7/68747470733a2f2f696d6775722e636f6d2f336736344f48392e6a7067)
> 
> The only way I think this would be doable is to manually check for each video if the closed captions are available

Well, I can see `Subtitles/CC` in the filters :).

**Comment by Hexer10** [comment]
I guess I'm blind... totally missed it, I'll check how to implement it : P

**Comment by Hexer10** [comment]
Now you can use the filters, starting from version `1.9.0-nullsafety.6`. 

As of now they cannot be merged (the filters), and won't be for quite sometime, unless someone wants do submit a pr.

To use them you can do as such:
```
yt.search.getVideos('hello', filter: filters.features.subTitles);
```

I'm not yet sure if I'm gonna leave the `filters` as a top-level variable or not, let me know if you have any suggets.

**Comment by tuanbs** [comment]
@Hexer10 You're amazing. Thank you very much Sir. Now I'm able to get the search videos based on the Subtitle/CC filter:
```dart
var _youtubeExplode = YoutubeExplode();
SearchList _searchList;
_searchList = await _youtubeExplode.search.getVideos(query, filter: filters.features.subTitles);
// _searchList = _searchList.where((item) => item?.isLive == false).toList();
_searchList.forEach((searchVideo) {
    print(searchVideo.channelId?.value);
});
```
The thing is I'm just wondering why the line `_searchList = _searchList.where((item) => item?.isLive == false).toList();` causes the runtime error and the line `print(searchVideo.channelId?.value);` always return `Null` value.
I know this addition question is not related to the current issue. Please let me know if I should open a new issue for this question.
Again, thank you very much for adding this feature. Please accept my donation as a beer for you. Cheers.

**Comment by Hexer10** [comment]
> @Hexer10 You're amazing. Thank you very much Sir. Now I'm able to get the search videos based on the Subtitle/CC filter:
> 
> ```dart
> var _youtubeExplode = YoutubeExplode();
> SearchList _searchList;
> _searchList = await _youtubeExplode.search.getVideos(query, filter: filters.features.subTitles);
> // _searchList = _searchList.where((item) => item?.isLive == false).toList();
> _searchList.forEach((searchVideo) {
>     print(searchVideo.channelId?.value);
> });
> ```
> 
> The thing is I'm just wondering why the line `_searchList = _searchList.where((item) => item?.isLive == false).toList();` causes the runtime error and the line `print(searchVideo.channelId?.value);` always return `Null` value.
> I know this addition question is not related to the current issue. Please let me know if I should open a new issue for this question.
> Again, thank you very much for adding this feature. Please accept my donation as a beer for you. Cheers.

Thanks for the donation, I really appreciate it!

Unfortunately currently searching a video does not provider the video channel it, but only the video author's name, I should be able to implement the channelId as well in the coming days

**Comment by Hexer10** [comment]
@tuanbs just published `1.9.0-nullsafety.7`, now your code should be working correctly

**Comment by lrorpilla** [comment]
Hi, just wondering, is this feature able to filter closed captions by language? 

Presently in my app, I'm able to show which videos have Japanese closed captions by querying the TimedText XML where the subtitles are stored given a video ID, but it would be greatly beneficial if I could improve this to filter the search for a specific language to begin with.

**Comment by Hexer10** [comment]
> Hi, just wondering, is this feature able to filter closed captions by language?
> 
> Presently in my app, I'm able to show which videos have Japanese closed captions by querying the TimedText XML where the subtitles are stored given a video ID, but it would be great if I could improve my app to be able to filter the search for a specific language to begin with.
> 
> Much appreciated.

Unfortunately I don't think it is possibile to select CC by language directly in the search query, since youtube doesn't expose that information in the search page.
