### ISSUE TITLE
Silent option/verbose toggle

### ISSUE THREAD

**Issue by mymikemiller** [Hexer10/youtube_explode_dart#116]
**Is your feature request related to a problem? Please describe.**
I get a lot of verbose output when using the api, for example, when requesting information on a video:

```
Request: GET https://youtube.com/watch?v=XRi7F7Xd3xI&bpctr=9999999999&hl=en
Request: GET https://youtube.com/get_video_info?video_id=ZBiDdSOyEQE&el=embedded&eurl=https://youtube.googleapis.com/v/ZBiDdSOyEQE&hl=en
Request: GET https://youtube.com/watch?v=ZBiDdSOyEQE&bpctr=9999999999&hl=en
Request: GET https://youtube.com/get_video_info?video_id=ll04irMoOHA&el=embedded&eurl=https://youtube.googleapis.com/v/ll04irMoOHA&hl=en
```

and when downloading a video:

```
Request: get https://r3---sn-bvvbax4pcxg-naje.googlevideo.com/videoplayback?expire=1616722254&ei=7uRcYKLyBYyTkwbEpangBw&ip=136.36.158.195&id=o-APSSsct0cASGpO9VLnBZW0VzGRaZ4rsJfAELLZFFdKPy&itag=18&source=youtube&requiressl=yes&mh=cC&mm=31%2C29&mn=sn-bvvbax4pcxg-naje%2Csn-a5meknzr&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=1392500&vprv=1&mime=video%2Fmp4&ns=N1Zzw87EXIGT_q9Wsnn0lqEF&gir=yes&clen=73556993&ratebypass=yes&dur=1866.001&lmt=1615959275437287&mt=1616700280&fvip=3&fexp=24001373%2C24007246&c=WEB&txp=6310222&n=ZyJFtH7T9OYTYGCFezTFY&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPQw4EfJ92NDV2kk65g0RVkvVQSh2VSDnLDKM2nKm4tzAiEA8oAc8kZHXsaS83KhXFZTSgC2bRlRfP_TmVD3iGbTs3w%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAP-CboqkNEbadiv0cAp41gWfupSVhP3CPNti40r2JrjdAiEA-p1CesTTymih3SIxuX8hYC49lA6Vc2k2xe0BvzdyHoM%3D
```

**Describe the solution you'd like**
I'd like a way to silence this type of output so my logs don't become so cluttered.

**Describe alternatives you've considered**
I could do some finagling rerouting stdout/stderr somewhere else during these calls, but I wouldn't want to miss out on important output/errors coming from the library

**How should this be implemented**
I don't think this output is particularly useful and could be disabled by default, perhaps adding a `verbose` option to the library to enable it.

**Comment by Hexer10** [comment]
I totally had forgotten to uncomment that line in a previus version please try to set your youtube_explode_dart to `1.9.0-nullsafety.7`.

**Comment by Hexer10** [comment]
Should be fixed, please reopen if this still happens on the latest version.
