### ISSUE TITLE
yt.videos.get fail

### ISSUE THREAD

**Issue by francigueco** [Hexer10/youtube_explode_dart#118]
Hi, yt.videos.get function has stopped working. Returns an exception when executed.

To Reproduce:
```
var yt = youtube.YoutubeExplode();
var video = await yt.videos.get('https://youtu.be/d99LKvKS0zI');

```
Catch error:
![error](https://user-images.githubusercontent.com/51756685/113475724-9cf12300-9477-11eb-9a5d-e88ff8ddc2d3.jpg)

 - Enviroment: Flutter
 - YoutubeExplode Version ^1.8.0

**Comment by Hexer10** [comment]
Please use the latest version of the library: `^1.9.1`, youtube frequently changes it's format
