### ISSUE TITLE
[BUG] The video only streams give error 403

### ISSUE THREAD

**Issue by ankurxshukla** [Hexer10/youtube_explode_dart#120]
**Describe the bug**
When I try to extract the video only streams, the URLs give error 403. The muxed and audio only streams work fine.

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
List<VideoOnlyStreamInfo> videoStreams = [];
List<MuxedStreamInfo> muxedStreams = [];
List<AudioOnlyStreamInfo> audioStreams = [];

final yt = YoutubeExplode();

final manifest = yt.videos.streamsClient.getManifest(widget.lecture.url);
    manifest.then((value) {
      setState(() {
        videoStreams = value.videoOnly.toList();
        audioStreams = value.audioOnly.toList();
        muxedStreams = value.muxed.toList();
      });
    });

for(final i in videoStreams) {
    //None of these urls work
    print(i.url);
}
```

**Enviroment: (please complete the following information):**
 - Enviroment: Android Virtual machine
 - YoutubeExplode Version ^1.9.1

**Additional context**
I guess this is because of some request headers missing

**Comment by lrorpilla** [comment]
I can't seem to use the `yt.videos.get` method right now as well.

**Comment by ankurxshukla** [comment]
This seems to work on some of the videos, but on most of the other videos it doesn't.

**Comment by Hexer10** [comment]
Most likely youtube changed something, since this was reported in YouTube explode as well ( https://github.com/Tyrrrz/YoutubeExplode/issues/530 ).

**Comment by ankurxshukla** [comment]
@Hexer10 can you please fix this issue? I am being too lazy to implement URL deciphering from scratch.

**Comment by Hexer10** [comment]
I'm not sure what the cause would be at the moment. When I've some time I'll try to reproduce and check it out

**Comment by lrorpilla** [comment]
The videos seem to be working on my app again, haven't touched the code.

**Comment by lrorpilla** [comment]
And it seems to be broken again. Guess it'll change here and there.

**Comment by Hexer10** [comment]
Youtube is known for this kind of inconsistences, I've tried running the tests on my pc today and all worked fine. I guess that at the moment there's nothing that can be done from the library-side.

You should either wait some time, or inject an HttpClient which has a logged youtube user cookies
