### ISSUE TITLE
Get multiple resolution muxed streams for live videos

### ISSUE THREAD

**Issue by ankurxshukla** [Hexer10/youtube_explode_dart#121]
YouTube livestreams have multiple resolution muxed streams. I know its possible to extract them and not just the best one.

**Comment by Hexer10** [comment]
What do you mean? I'm aware that the muxed streams are available only in low quality, but that's how youtube provides them, if you want higher quality with both audio and video you should download two streams separately and the merge them with tools like ffmpeg

**Comment by ankurxshukla** [comment]
I meant only for the live streams on youtube, there is only one method to extract the url, i.e. getHttpsLiveStreamUrl. I wonder if its possible to get all different quality streams available.

**Comment by ankurxshukla** [comment]
There is this repo: [YouTubeExtractor](https://github.com/nhCoder/YouTubeExtractor), I guess it has a few more methods available than YouTube explode. I wonder if its possible to port better parts of this repo.

**Comment by Hexer10** [comment]
What features of that library are you looking for exactly?

**Comment by ankurxshukla** [comment]
I wanted to get multiple quality muxed stream links for youtube live videos. Currently only single link is generated for live videos using the getHttpsLiveStreamUrl method.
