### ISSUE TITLE
How to import 1.9.3 version of this plugin in non null safety application

### ISSUE THREAD

**Issue by tahercoolguy** [Hexer10/youtube_explode_dart#123]
I have application which previously had 1.7.5 version of this plugin . But now I want to upgrade to new version of this plugin . But as i am from non null safety application .  New version of this plugin is not upgraded because new version is null safety plugin . 

Can anybody please let me if I want to upgrade to new version of this plugin to non null safety application. Can we do it 

Please help me as I am new to flutter

**Comment by Hexer10** [comment]
Even if you don't want to opt-in null safety you can still use this library, as long as you have at least a flutter sdk that is built on dart 2.12.0 or greater.
