### ISSUE TITLE
Feature request: Is it possible to get video info including links by inputting a keyword and not by videoId?

### ISSUE THREAD

**Issue by itssidhere** [Hexer10/youtube_explode_dart#124]
The YouTube api has a strong limitation of 10k. It would be great if we can have search by keyword.

**Comment by Hexer10** [comment]
What do you mean? There is already a search client

**Comment by itssidhere** [comment]
@Hexer10 I didn't see any search by query in the documentation.

**Comment by Hexer10** [comment]
@itssidhere Have a look here on how to use the search client
https://github.com/Hexer10/youtube_explode_dart/blob/297d2ce2a48983c2c572323b3619a3032c323052/test/search_test.dart#L15

**Comment by itssidhere** [comment]
@Hexer10  thanks bruh. It really helped. Just a question can we convert this search result to json?

**Comment by Hexer10** [comment]
> @Hexer10 thanks bruh. It really helped. Just a question can we convert this search result to json?

Not currently, you'd need to manually make the convertion

**Comment by itssidhere** [comment]
@Hexer10  Thanks for this awesome plugin. I am closing this issue.
