### ISSUE TITLE
Is someone using this plugin production apps? ( IOS and Android)

### ISSUE THREAD

**Issue by kalismeras61** [Hexer10/youtube_explode_dart#125]
I just wanted to ask , is there any issue publishing app stores with this plugin ?

**Comment by rootrxx** [comment]
this module is very bad I did everything to make it work in the implementation, but everything did not work out

**Comment by Hexer10** [comment]
> this module is very bad I did everything to make it work in the implementation, but everything did not work out

At least explain what doesn't work. Many people used this package and apart from when youtube breaks something it works properly.


By the way, I'm not sure if an app which downloads youtube videos using this package could be accepted on Android (even less on iOS). On Android third-party app stores could be a nice place to share them tough.

**Comment by Hexer10** [comment]
By the way, I'm not sure if an app which downloads youtube videos using this package could be accepted on Android (even less on iOS). On Android third-party app stores could be a nice place to share them tough.
