### ISSUE TITLE
Generated urls return Error 403

### ISSUE THREAD

**Issue by haidar786** [Hexer10/youtube_explode_dart#13]
Access to r7---sn-2uja-3ip6.googlevideo.com was denied. This is happening to all videos when playing by generated url.

**Comment by Hexer10** [comment]
Could you link a video which gives the error? Also, please post the code you're using

**Comment by haidar786** [comment]
[gist](https://gist.github.com/haidar786/42ded58f9ad2244c5117b916703d442a)
[generatedLink](https://r1---sn-1vob-aixl.googlevideo.com/videoplayback?expire=1583500643&ei=A_lhXq_yE5LVxwLk-5uQCw&ip=103.255.5.33&id=o-APIW3CZgbucNhW7JXdDt5uc039ZKTt0BXQmJ6hk7byi6&itag=133&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-1vob-aixl%2Csn-4wg7ln76&ms=au%2Crdu&mv=m&mvi=0&pl=24&usequic=no&initcwndbps=168750&vprv=1&mime=video%2Fmp4&gir=yes&clen=4060174&dur=146.396&lmt=1581973531352040&mt=1583478926&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cusequic%2Cinitcwndbps&lsig=ABSNjpQwRAIgHjkOcZR1pC_3BYkl59Tx1pQVaTt1JsXhtj8P910dkC4CICT9vFSL8uQ2ZJ8-IAq3Z8pT06QlJbKI-A8l1r-TiNrb&sig=UDKhkGAwRgIhAI71C5WAdOoy1E8ZFBNI2HCC0eGjOl47zx5IdTC3kM0pdiEA8NWG7IKRv1ZfAoNUueSnsD3u8uF%3DZfXCW2z0z8Ak2c0)
It gives error no matter what videoId i use.

**Comment by Hexer10** [comment]
Could you please try again now? Seems like it was an issue with YouTube

**Comment by Hexer10** [comment]
Also you're handling the YoutubeExplode instance in a bad manner, you are creating a new instance every time you call YoutubeExplode() and not closing it

**Comment by haidar786** [comment]
Yes, i tried again but same result. Youtube block those links. Maybe by using proxy or something solve that issue.

**Comment by haidar786** [comment]
Thanks for that. I will change instance handling.

**Comment by Ale0589** [comment]
Hey, this has been happening also to me today. Is there any fix?

**Comment by Hexer10** [comment]
At the moment I don't know why this is happening, since here is working properly (not consistently tough)

**Comment by Hexer10** [comment]
Related issue https://github.com/Tyrrrz/YoutubeExplode/issues/343

**Comment by Auties00** [comment]
This stopped happening for some days and now it happened again, any ideas?

**Comment by hahai96** [comment]
@Hexer10 Should I create a YoutubeExplode instance for the entire application?

**Comment by Hexer10** [comment]
> @Hexer10 Should I create a YoutubeExplode instance for the entire application?

In Flutter you could that if you plan to use the api multiple times through the app execution

**Comment by Hexer10** [comment]
Starting from version 0.0.15 an exception will be thrown, when a vide is not available, I guess there is no way to fix this properly.

**Comment by haidar786** [comment]
For me this error only happening to music videos. Other videos works fine.

**Comment by BeMacized** [comment]
Same thing is happening here, but the behavior seems to be really inconsistent. On some days the generated urls return a 403, while on others they work just fine, and this all for exactly the same (music) video.

**Comment by hahai96** [comment]
@Hexer10 Should throw exception when I get error code 403

**Comment by Hexer10** [comment]
The error is thrown only when you try to use the functions such as `downloadStream`, otherwise not. I did not send a `head`  request for every url that is generated (even tough most likely if one fails all the others will). So you should send a `head` requested before, and check the the status code

**Comment by dieunt** [comment]
@Hexer10 i get the same problem when using youtube-dl to download youtube, and it can be fix by using --cookie. Can you try to add cookie file to the request when send to youtube.com? 

You can get cookie by using various way, like chrome extension

**Comment by johnjames24** [comment]
> @Hexer10 i get the same problem when using youtube-dl to download youtube, and it can be fix by using --cookie. Can you try to add cookie file to the request when send to youtube.com?
> 
> You can get cookie by using various way, like chrome extension

I did it but did not work

**Comment by hidenori111yellow** [comment]
This may be helpful.
https://github.com/Tyrrrz/YoutubeExplode/issues/349

**Comment by Hexer10** [comment]
This is should be fixed in `1.0.0-beta`, you can already try it, but is still missing some features see( https://github.com/Hexer10/youtube_explode_dart/milestone/1 ), and has also some breaking changes, you can see how to library syntax change in the v5 branch which includes the updated README and examples, also check the pub.dev documentation: https://pub.dev/documentation/youtube_explode_dart/1.0.0-beta/ .
If you can any doubts about the update feel free to contact me.
