### ISSUE TITLE
FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.

### ISSUE THREAD

**Issue by tibfox** [Hexer10/youtube_explode_dart#130]
Hey there! 
I am using the latest version (1.9.4) of this package and get this: 
```
I/flutter (26799): FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
I/flutter (26799): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
I/flutter (26799): If this issue persists, please report it on the project's GitHub page.
I/flutter (26799): Request: GET https://youtube.com/get_video_info?video_id=Di2Bkufu4AQ&el=embedded&eurl=https://youtube.googleapis.com/v/Di2Bkufu4AQ&hl=en&html5=1
I/flutter (26799): Response: (404)
```
when trying this: 
```
var yt = YoutubeExplode();

      var video = await yt.videos.get('https://www.youtube.com/watch?v=jlTUhhHSX00');
```

They probably have changed something again. Thx for investigating!

**Comment by diegoalex** [comment]
Same issue here

**Comment by tuanbs** [comment]
Same error, please fix urgently.

**Comment by murilosamuel** [comment]
Same issue.

**Comment by arbile26** [comment]
Same issue

**Comment by Ahtram** [comment]
![Screen Shot 2021-06-18 at 4 27 53 PM](https://user-images.githubusercontent.com/1751201/122531704-595b8d80-d052-11eb-8999-7d9c5e04bd9c.png)
Same here

**Comment by Hexer10** [comment]
I could reproduce this, seems like youtube removed the endpoint to retrieve the video info. Check here for more info https://github.com/Tyrrrz/YoutubeExplode/issues/565 . As soon as there is a fix available I'll make update this package as well.

**Comment by Hexer10** [comment]
I've added a quick workaround the issue from: https://github.com/ytdl-org/youtube-dl/issues/29333#issuecomment-864049544 in v`1.9.5` which should kind of address the issue, since the endpoint could be completely removed in the future.
Also now seems like youtube doesn't send anymore the publish and upload date in that endpoint and sometimes it might take longer to load

**Comment by tibfox** [comment]
Thx for the quick workaround! Going to try that later and let you know if it works for me

**Comment by tuanbs** [comment]
After upgrading to version `1.9.5`, I got another error:
```bash
_CastError (Null check operator used on a null value)
_column: null
_errorMsg: "Null check operator used on a null value"
_line: null
_stackTrace: #0      ClosedCaptionTrack.languageName (package:youtube_explode_dart/src/reverse_engineering/responses/player_response.dart:151:74)
#1      ClosedCaptionClient.getManifest (package:youtube_explode_dart/src/videos/closed_captions/closed_caption_client.dart:45:48)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
...
```

**Comment by tibfox** [comment]
@tuanbs that's probably because a value is returned as null and you are checking it with ! within your code. Debug your code and you will find the null value ;) 

@Hexer10 The workaround works for me

**Comment by tuanbs** [comment]
@tibfox As you can see from the log above it's clearly from the package itself:
```bash
_errorMsg: "Null check operator used on a null value"
_line: null
_stackTrace: #0      ClosedCaptionTrack.languageName (package:youtube_explode_dart/src/reverse_engineering/responses/player_response.dart:151:74)
```
I found out a workaround after debugging the package based on the log file `youtube_explode_dart/src/reverse_engineering/responses/player_response.dart` at line `151`:
Change this line:
```dart
String get languageName => root.get('name')!.getT<String>('simpleText')!;
```
into this:
```dart
String get languageName => root['name']['runs'][0]['text'];
```

Hope it helps for the next version. Thanks for this awesome plugin. Please keep evolving it.

**Comment by Hexer10** [comment]
Just pushed a new version that fixes the ClosedCaptions issue
