### ISSUE TITLE
publishDate broken

### ISSUE THREAD

**Issue by 89z** [Hexer10/youtube_explode_dart#131]
Using version 1.9.5, with this program:

~~~dart
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

void main() async {
   var yt = YoutubeExplode();
   var video = await yt.videos.get('https://youtube.com/watch?v=Dpp1sIL1m5Q');
   print(video.publishDate);
   yt.close();
}
~~~

I get `null` output. I believe the issue is here:

https://github.com/Hexer10/youtube_explode_dart/blob/4298ea7e396ff01316f635f5fa29cff975f1480c/lib/src/reverse_engineering/responses/player_response.dart#L38-L42

in that as of within the last 24 hours, I dont think `get_video_info` is able to return the `microformat` struct anymore.

**Comment by saelco** [comment]
same here. any solve?

**Comment by Hexer10** [comment]
Unfortunately youtube the youtube endpoint we are using doesn't send the `publishDate`/`uploadDate` anymore (most of the times). In the future another endpoint will be needed to be used to fetch that info (maybe scraping the webpage(?)). Altought I cannot give any ETA at the moment.

**Comment by mymikemiller** [comment]
I don't notice a deprecation notice in the [revision history](https://developers.google.com/youtube/v3/revision_history) for this. I feel like this might just be a bug on Google's end.

**Comment by mymikemiller** [comment]
Oh, I see. It IS being returned from the API, but youtube_explode doesn't use the API. I did some poking around in the dev tools network tab on refresh of a video but couldn't see where the date comes through. I'm not sure how it gets rendered to the page without coming through in a network request somewhere...

**Comment by Hexer10** [comment]
> Oh, I see. It IS being returned from the API, but youtube_explode doesn't use the API. I did some poking around in the dev tools network tab on refresh of a video but couldn't see where the date comes through. I'm not sure how it gets rendered to the page without coming through in a network request somewhere...

I found out that the publish/upload date appears in the meta tag.

Using these code in the dev console you give the value:
```
document.querySelector('meta[itemprop=uploadDate]').content
document.querySelector('meta[itemprop=datePublished]').content
```

**Comment by mymikemiller** [comment]
@Hexer10 This is great! Are you working on an update that uses this? I'll try to put together another PR if you're not already on top of it.

**Comment by Hexer10** [comment]
@mymikemiller I just pushed a new version: `1.9.8+1` which should address this issue! Please let me know if this still happens.

**Comment by mymikemiller** [comment]
Working for me! Thanks!
