### ISSUE TITLE
Getting 404 get error using YoutubeExplode

### ISSUE THREAD

**Issue by corcomm** [Hexer10/youtube_explode_dart#132]
Running on Android emulator:
(Was working previously- about a week ago.  Stopped working with message below without code change.)

var videoId = 'https://www.youtube.com/watch?v=xxxx';
var yt = YoutubeExplode();
yt.videos.get(videoId).then((video) {
...
})

Giving:

E/flutter ( 5767): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
E/flutter ( 5767): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
E/flutter ( 5767): If this issue persists, please report it on the project's GitHub page.
E/flutter ( 5767): Request: GET https://youtube.com/get_video_info?video_id=xxxx&el=embedded&eurl=https://youtube.googleapis.com/v/xxxx&hl=en&html5=1
E/flutter ( 5767): Response: (404)

Note: videoid above (an actual valid videoid has been used during execution)...
Note: browing to https://youtube.com/get_video_info manually also gives 404 error...

pubspec.yaml:

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart:
  ...

**Comment by Hexer10** [comment]
Should be fixed in the latest version (v`1.9.5` or greater)
