### ISSUE TITLE
How to get channel info

### ISSUE THREAD

**Issue by rupamking1** [Hexer10/youtube_explode_dart#133]
How to get Channel Info

**Comment by Hexer10** [comment]
Please post more info, what have you tried?

**Comment by rupamking1** [comment]
1. I need to get All Playlist Data,
2. Get Playlist videos

**Comment by Hexer10** [comment]
Jus have a look at the [README](https://github.com/Hexer10/youtube_explode_dart#working-with-playlists), there is specifically documentation about that.

**Comment by rupamking1** [comment]
get all videos and playlist of a channel this feature is not available in your package please add this
