### ISSUE TITLE
[BUG]Could not listen to download streams using stream controller

### ISSUE THREAD

**Issue by sunnypaul19999** [Hexer10/youtube_explode_dart#137]
**Could not listen to download streams**
```dart
//before this code ran successfully in 1.9.6
Stream<int> download(var streamToDownload, var title) async* {
    var stream = _streamInfo.yt.videos.streamsClient.get(streamToDownload);
    var fileSizeInBytes = streamToDownload.size.totalBytes;
    var filename = removeInvalidCharacters(title);
    //print('------->$filename');
    var file = File('E:\\$filename.${streamToDownload.container}');
    var filestream = file.openWrite();
    int prevProg = -1;
    int currProg = 0;
    await for (var bytesList in stream) {
      filestream.add(bytesList);
      //sending progress as stream to the subscriber
      currProg = ((file.lengthSync() / fileSizeInBytes) * 100).toInt();
      if (currProg > prevProg) {
        prevProg = currProg;
        yield (currProg);
      }
    }

    await filestream.flush();
    await filestream.close();
  }
```
**issue when I try to listen to download()**
```dart
 var progStream = download(streamInfo, 'title');
 progStream .listen((event) {}); //this gives error
/*whereas this runs fine
await for(int prog in stream) print(prog);*/
```
**Stack Strace**
Unhandled exception:
Null check operator used on a null value
#0      IOClient.send (package:http/src/io_client.dart:30:36)
#1      YoutubeHttpClient.send (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:158:24)
#2      YoutubeHttpClient.getStream.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:108:44)
#3      retry (package:youtube_explode_dart/src/retry.dart:17:28)
#4      YoutubeHttpClient.getStream (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:108:32)
<asynchronous suspension>
#5      Download.download (package:ytload/Download/Download.dart:24:5)

**Comment by Kakandas** [comment]
Does anybody have to answer on how to listen to the stream?
