### ISSUE TITLE
Fetch Subscribers by channel id

### ISSUE THREAD

**Issue by prateekmedia** [Hexer10/youtube_explode_dart#139]
I want to fetch subscribers by channel.

I can see that this library is only fetching id, title and logoUrl of a channel but can you also fetch subsribers, It can be a nullable int, as some people also disable their subscribers.
NewPipe and FreeTube already have this feature so can we have it on this library too.

Thank you!

**Comment by Hexer10** [comment]
I was looking into implementing this, but seems like youtube does only send an approximate of the total:

```
      "subscriberCountText": {
        "accessibility": {
          "accessibilityData": {
            "label": "670K subscribers"
          }
        },
        "simpleText": "670K subscribers"
      },
```

Do you know how the other libraries handle it? Should I give just the string output or convert to an int, eg:
'123' -> '123'
`10K` -> `10000`
`3.1M` -> `3100000`

**Comment by prateekmedia** [comment]
@Hexer10 int would be good as people who want to do something with that int can have the flexiblity, also some other regions doesn't use million and billion so it would be useful to convert the int according to there region.

Also will you make the fetching replies system work? It has been done by FreeTube but I don't know how they did it.

**Comment by Hexer10** [comment]
@prateekmedia I guess I'll just covert that value to an int.

By fetching what do you mean? The comments replies?

**Comment by Hexer10** [comment]
I added the subs count (`channel.subscribesCount`) in v`1.9.10`.

**Comment by prateekmedia** [comment]
@Hexer10 Yeah comment replies although it will for another issue.
