### ISSUE TITLE
Link gives 403 access denied

### ISSUE THREAD

**Issue by harshraj21** [Hexer10/youtube_explode_dart#140]
**Describe the bug**
The url returned by the below code does not works always leads to a 403 page access denied

**To Reproduce**
```dart
var yt = YoutubeExplode();
var video = await yt.videos.get('https://youtube.com/watch?v=BBAyRBTfsOU');
var manifest = await yt.videos.streamsClient.getManifest(video.id); //or directly us the id here BBAyRBTfsOU both results in same
print(manifest.videoOnly.first.url); //1080p video
```

**Enviroment**
 - Enviroment: [Flutter o Dart VM]
 - System: [Linux Ubuntu 20,04 LTS]
 - Version [Flutter 2.2.2]
 - YoutubeExplode Version [^1.9.9]

**Additional context**
Kindly do let me know how to fix this issue.
> while using the youtube-dl python(<a href="https://pypi.org/project/youtube_dl/">here</a>) to extract the link that link works flawlessly this means the issue is related to this package

![Screenshot from 2021-07-14 17-49-00](https://user-images.githubusercontent.com/49561994/125621194-a5680751-5fd4-4171-b926-05be55a70b91.png)

**Comment by Hexer10** [comment]
I couldn't reproduce your issue on my end, here the video loads correctly in the browser. Please try one of the following:
If you are using a VPN try disabling it.
Try opening the link in an icognito browser.
Make sure to copy the full URL.

**Comment by Danesz** [comment]
I am getting this error too.
Maybe some cookies/headers/etc is missing if we try to open the URL outside of YoutubeExplode?

The use-case I try to achieve:
1. get the video URL with YoutubeExplode
2. Play the URL with a video player component on the device.

The issues is that any url I get back from YoutubeExplode, is giving 403. 
(e.g. 
https://rr9---sn-uxaxoxu-cg0r.googlevideo.com/videoplayback?expire=1709225284&ei=5GDgZdiHM7-HvdIP5o-MgAw&ip=84.198.147.154&id=o-AHCjTflqW34wADxLcGoP-RJe6H6hJZIMSI10sr8TByPu&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=jR&mm=31%2C29&mn=sn-uxaxoxu-cg0r%2Csn-5hnekn7s&ms=au%2Crdu&mv=m&mvi=9&pl=13&initcwndbps=1698750&spc=UWF9f_RDvPltPIOUkrtIZT5g4ZpzNUvaxbi84kNn4E5CiMk&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=21855464&dur=94.749&lmt=1708544866553142&mt=1709203027&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgdkg8XfHhE5pa1OuvkHq6fjawOY8pW94OQJoE1-I1v38CIE4XX_6lDmIM6KYiWbk7gics9LUR8qoxSyuMH49bbq1H&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIhAL2HQJvd9D6KtG2r_v2FFMMrmEJuaaZH5v1eKIkzpssGAiAc7wdd0lvz0Xo1Cd5wCh2rK9oVFCpVBDAgvU305jnznA%3D%3D)
