### ISSUE TITLE
The converted url does not work the next day.

### ISSUE THREAD

**Issue by KOSNOWMAN** [Hexer10/youtube_explode_dart#143]
If the url generated by applying the code as shown below is generated in video_player, it works well. However, if I save this url and play it the next day, it doesn't work. what is the reason?

.............  
final extractor = YoutubeExplode();
final videoId = convertUrlToId(videoUrl);
final streamManifest = await extractor.videos.streamsClient.getManifest(videoId);
final streamInfo = streamManifest.muxed.withHighestBitrate();
extractor.close();
return streamInfo.url.toString();
..............

this is the saved url. 

https://r1---sn-n3cgv5qc5oq-bh2l6.googlevideo.com/videoplayback?expire=1626550978&ei=Yt7yYKX7D9yMlQTPyKTICg&ip=218.39.17.80&id=o-AD4F3gnoWr3HAJ3eKse4GSo-eqj5q15WdoMH5cEMLL1C&itag=18&source=youtube&requiressl=yes&mh=Xx&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2l6%2Csn-3pm7dn7z&ms=au%2Conr&mv=m&mvi=1&pl=20&gcr=kr&initcwndbps=1500000&vprv=1&mime=video%2Fmp4&ns=gRIHqJVFMgXXyNSPYDrir6wG&gir=yes&clen=13941774&ratebypass=yes&dur=165.767&lmt=1625380971121921&mt=1626529023&fvip=1&fexp=24001373%2C24007246&c=TVHTML5&txp=5530434&n=dsZcMDUJ8etvBlau&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKdRQOOpWWcnmPDKbHzwFDnf72DhNlNuRG5PoTm6Ry7iAiEA5c5Zxh0RQSg8_ipJdYmFD385xERlsCUR0X1KhJ5iCaY%3D&sig=AOq0QJ8wRQIgVIor7adXc3nYtPuJf5V1PKIXw7ife6jBIgYiO5Tl2BcCIQC0EvV1qUlvW-B9_XDbMuSaqjso95I9U1TCn-hk5EfGMA%3D%3D

**Comment by Hexer10** [comment]
You can't cache that url, YouTube invalidates it after a certain time is passed. You can see that the first url parameter is `expire`, tough I'm not sure how to parse it.
