### ISSUE TITLE
EMBEDDED client

### ISSUE THREAD

**Issue by 89z** [Hexer10/youtube_explode_dart#147]
To address this comment [1]:

> That's quite a sizeable amount of videos now inaccessible.

Yes and no. You cant get "level 3" videos anymore without authentication, but you can still get "level 1", and you can also get "level 2" if you use an embedded client:

~~~
"ANDROID_EMBEDDED_PLAYER", "16.20"
"WEB_EMBEDDED_PLAYER", "1.20210620.0.1"
~~~

https://github.com/Hexer10/youtube_explode_dart/blob/e8ac71ff441b2293b0fb1491db51ccc192a4240b/lib/src/reverse_engineering/youtube_http_client.dart#L156-L160

1. https://github.com/Hexer10/youtube_explode_dart/issues/144#issuecomment-885277354

**Comment by Hexer10** [comment]
What are you talking about? 
Could you send an example of a level1 or level2 video?

Also that endpoint has nothing to do with fetching videos, but it used to call the yt api for example to fetch the comments

**Comment by Hexer10** [comment]
I implemented the embedded client in v`1.10.3`. Now more videos should be available.

**Comment by 89z** [comment]
this is bad, because some videos DONT work on embed, that DO work on the regular client `ANDROID`:

https://www.youtube.com/embed/MeJVWBSsPAY

So you need a way for the user to choose, or maybe have the code try both internally.

**Comment by Hexer10** [comment]
Yeah I noticed that's indeed the code first tries to use the embedded client and if that fails it tries to parse the video streams like before ( from the watchpage ).
