### ISSUE TITLE
[BUG] 1.10.4 doesn't compatible with newest Flutter sdk

### ISSUE THREAD

**Issue by Ahtram** [Hexer10/youtube_explode_dart#148]
Hi, 
[
![Screen Shot 2021-07-26 at 1 09 09 PM](https://user-images.githubusercontent.com/1751201/126936309-541e90c1-fb9d-4d5d-9a1c-8e86f63552de.png)
](url)

And 

![Screen Shot 2021-07-26 at 1 11 25 PM](https://user-images.githubusercontent.com/1751201/126936336-bceaf2b4-50b4-49d5-9f79-ea60d3c73310.png)

Thank you for the good work!

**Comment by mirkarpude** [comment]
Any solution?

**Comment by Hexer10** [comment]
Seems this is an issue with `freezed` ( https://github.com/rrousselGit/freezed/issues/485 )

To fix the issue until a new `flutter` version is release you can temporarily add this to your pubspec.yaml
```
dependency_overrides: 
  freezed_annotation: 0.14.2
```

**Comment by mirkarpude** [comment]
Thanks
Now as per @Hexer10 
dependency_overrides: 
  freezed_annotation: 0.14.2
  meta: 1.3.0

**Comment by JellyO1** [comment]
It would probably be better to just change the `json_annotation` dependency to 4.0.1.

**Comment by CARocha** [comment]
Any update for this? i need update 1.10.4 to 1.10.6 in flutter version 2.2.2 is posible? or need alway put dependency overrides freezed_annotation and meta??

**Comment by prateekmedia** [comment]
@Hexer10 This should be closed now with flutter using meta 1.7.0 in latest stable release.
