### ISSUE TITLE
Get comments count

### ISSUE THREAD

**Issue by prateekmedia** [Hexer10/youtube_explode_dart#150]
Can I get total number of comments from a video like a `commentCount` variable similar to `replyCount` is for comment but for videos.

**Comment by prateekmedia** [comment]
This request is due to the fact that when we take comment using comment client, then its length reports to be 20 for any kind of video.

**Comment by Hexer10** [comment]
Yeah, that happens because the YouTube endpoint returns the videos a batch of max 20 videos per request (you can keep fetching using comments.nextPage()). I'll add a getter to retrieve the total comments right away.

**Comment by Hexer10** [comment]
`CommentList.totalLength` since v`1.10.5` returns the total comments count of a video.

**Comment by prateekmedia** [comment]
@Hexer10 Actually I have two problems with it:
1) The CHANGELOG is wrong and has `totalCount` instead of `totalLength`.

2) CommentsList is not exposed or exported, So It results in no type `CommentsList` found.
https://github.com/Hexer10/youtube_explode_dart/blob/3e5effed2f9be48298df8ac0ba0a796a2bf7f473/lib/src/videos/comments/comments.dart#L1-L2

**Comment by Hexer10** [comment]
@prateekmedia Thanks! I've fixed the typo in the changelog and exported the `CommentsList` (I didn't catch that issue since I usually just do `final list = CommentsClient.get(...)` and the analyzer just infers the type).

Just update to v`1.10.5+1`
