### ISSUE TITLE
Is playstore / Appstore accept ?

### ISSUE THREAD

**Issue by mvphaneendra** [Hexer10/youtube_explode_dart#152]
is it valid to read youtube public video data, without API key ?
is playstore / appstore accept our App to release ?

plz answer

**Comment by sunnypaul19999** [comment]
you can check this article
https://www.makeuseof.com/tag/is-it-legal-to-download-youtube-videos/

**Comment by sunnypaul19999** [comment]
This issue is not a bug

**Comment by Flajt** [comment]
I managed to get my App into early access for the PlayStore, I think you should add some form of disclaimer. For Apple you might need provide some links that you don't steal content (I guess the Youtube Api terms etc. but idk for sure) / are allowed to use the videos / api.

**Comment by Hexer10** [comment]
I'm not sure if there are any issues publishing an app on either store using this package. There could be some restriction if you download videos (streaming as well(?) ). But I guess there shouldn't be any issues if you just fetch a video info.

DISCLAMER: I'm not a lawyer so don't take anything I've said for granted, these are just my guesses/suggestions.

**Comment by shinewanna** [comment]
I know playstore not allow if the app has youtube video downloading feature. And there's no Youtube downloader app on playstore.
But i found youtube downloader apps on appstore, that weird, and that apps are work. i don't know is appstore is allow or if someone has experience, feel free to share it.
