### ISSUE TITLE
[BUG] Wrong container name for Audio-only stream

### ISSUE THREAD

**Issue by prateekmedia** [Hexer10/youtube_explode_dart#153]
**Describe the bug**
stream.container.name returns mp4 even for Audio only streams.

**To Reproduce**
Access container name property of a audio only video stream and it will result in mp4 and not webm or m4a or ogg

**Comment by 89z** [comment]
example video?

**Comment by prateekmedia** [comment]
Any video?

**Comment by prateekmedia** [comment]
@89z try any random video

**Comment by 89z** [comment]
example video?

**Comment by sunnypaul19999** [comment]
> **Describe the bug**
> stream.container.name returns mp4 even for Audio only streams.
> 
> **To Reproduce**
> Access container name property of a audio only video stream and it will result in mp4 and not webm or m4a or ogg

The package always uses either mp4, WebM, and 3gp as *containers* for video and audio stream.
It does not always result in mp4.
 For codec for audio only  stream you can check the audioCodec.

**Comment by prateekmedia** [comment]
@sunnypaul19999 Thanks.

**Comment by Hexer10** [comment]
@prateekmedia as sunnypaul19999 said, youtube doesn't return any .mp3 stream, even for audio-only streams, so that's why there are no .mp3 containers
