### ISSUE TITLE
[BUG]Incorrect video stream type is returned

### ISSUE THREAD

**Issue by sunnypaul19999** [Hexer10/youtube_explode_dart#154]
**Incorrect video stream type is returned**
when I am downloading https://www.youtube.com/watch?v=cSLAO7zxS2M at 1080p although I was getting a Muxed
type stream but the stream being downloaded has no audio.

**Comment by 89z** [comment]
title says incorrect video, but comment says no audio - can you clarify?

**Comment by sunnypaul19999** [comment]
when I am getting the StreamInfo of this video  https://www.youtube.com/watch?v=cSLAO7zxS2M at 1080p I am getting MuxedStreamInfo object on calling toString() I  get output Muxed (137 | 1080p | mp4) which is muxed stream. So this stream should contain both audio and video but now when I downloading this video I am getting an mp4 container containing only the video stream no audio stream.
I saw this problem with a few other videos I tried out.

**Comment by sunnypaul19999** [comment]
> title says incorrect video, but comment says no audio - can you clarify?

I have said incorrect video stream type as I am getting video only for MuxedStreamInfo.
As the stream contains only video then I should have gotten VideoOnlyStreamInfo not MuxedStreamInfo

**Comment by Hexer10** [comment]
For some reason youtube returns a mimetype that should include the videos as well, but actually it doesnt, the other way around happens as well, where the video is present but the audio not. I'll check if there is any meaningful way to disgnguish between theese streams.

![image](https://user-images.githubusercontent.com/21113203/128598510-14da33ce-13f9-448b-9a8d-b78921a6298d.png)

(this should be muxed but doesn't cotain audio, I could also reproduce .mp4 files that had no video)

**Comment by sunnypaul19999** [comment]
thanks for clarification

**Comment by sunnypaul19999** [comment]
> For some reason youtube returns a mimetype that should include the videos as well, but actually it doesnt, the other way around happens as well, where the video is present but the audio not. I'll check if there is any meaningful way to disgnguish between theese streams.
> 
> ![image](https://user-images.githubusercontent.com/21113203/128598510-14da33ce-13f9-448b-9a8d-b78921a6298d.png)
> 
> (this should be muxed but doesn't cotain audio, I could also reproduce .mp4 files that had no video)

thanks for clarification

**Comment by Hexer10** [comment]
This should be fixed see #162
