### ISSUE TITLE
[BUG] FatalFailureException Response: (410)

### ISSUE THREAD

**Issue by astroxd** [Hexer10/youtube_explode_dart#155]
**Describe the bug**
![image](https://user-images.githubusercontent.com/48565568/128566179-c475e079-c037-4c52-bd30-2b5880a017bc.png)

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
var yt = youtubeExplode.YoutubeExplode();
    String videoID = videoURL.split('/').last;

    //* Get video metadata
    var video = await yt.videos.get(videoID);
```

**Stacktrace**
Include here the stacktrace (if applicable). 

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter]
 - Version [e.g. 2.8.4]  sdk: ">=2.12.0 <3.0.0", version: 1.0.0+1, Flutter: 2.2.3
 - YoutubeExplode Version [^1.9.10]
**Additional context**

**Comment by Hexer10** [comment]
This is already fixed, please use version `1.10.4`
