### ISSUE TITLE
[BUG] [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure

### ISSUE THREAD

**Issue by Alleny244** [Hexer10/youtube_explode_dart#157]
**Describe the bug**

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
 Future<void> getName() async {
      var yt = YoutubeExplode();
      var video =
          await yt.videos.get('https://www.youtube.com/watch?v=VPc-Muhi_y4');

      print('Title: $video');

      // Close the YoutubeExplode's http client.
      yt.close();
    }

    getName();
  }
```

**Stacktrace**
Include here the stacktrace (if applicable). 
E/NetdClient( 9291): querySockNetidForUid nid:0, uid:10396, command.cmdId:11, id:0
E/flutter ( 9291): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
E/flutter ( 9291): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
E/flutter ( 9291): If this issue persists, please report it on the project's GitHub page.
E/flutter ( 9291): Request: GET https://youtube.com/get_video_info?video_id=VPc-Muhi_y4&el=embedded&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FVPc-Muhi_y4&hl=en&html5=1&c=TVHTML5&cver=6.20180913
E/flutter ( 9291): Response: (410)
E/flutter ( 9291):
E/flutter ( 9291): #0      YoutubeHttpClient._validateResponse (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:49:7)
E/flutter ( 9291): #1      YoutubeHttpClient.getString (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:59:7)
E/flutter ( 9291): <asynchronous suspension>
E/flutter ( 9291): #2      VideoInfoResponse.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/responses/video_info_response.dart:73:17)
E/flutter ( 9291): <asynchronous suspension>
E/flutter ( 9291): #3      retry (package:youtube_explode_dart/src/retry.dart:17:14)
E/flutter ( 9291): <asynchronous suspension>
E/flutter ( 9291): #4      VideoClient._getVideoFromWatchPage (package:youtube_explode_dart/src/videos/video_client.dart:32:9)
E/flutter ( 9291): <asynchronous suspension>
E/flutter ( 9291): #5      _YoutubeState.initState.getName
package:yfitube/pages/youTube.dart:16
E/flutter ( 9291): <asynchronous suspension>

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - Version [e.g. 2.8.4]
 - YoutubeExplode Version [e.g. ^2.5.0]
**Additional context**

**Comment by Hexer10** [comment]
Please follow the issue form and provide  all the necessary information. Also make sure to try on the latest stable, this issue has already been fixed
