### ISSUE TITLE
Channel Video Count

### ISSUE THREAD

**Issue by rohanpanuganti** [Hexer10/youtube_explode_dart#161]
Is it possible right now to get the video count for a specific channel?

**Comment by Hexer10** [comment]
You have the `.subscribersCount` getter on a `Channel` instance 

https://github.com/Hexer10/youtube_explode_dart/blob/3e5effed2f9be48298df8ac0ba0a796a2bf7f473/test/channel_test.dart#L21

**Comment by rohanpanuganti** [comment]
I was asking if there was a `.videoCount` getter.

**Comment by Hexer10** [comment]
@rohanpanuganti I'm sorry, I just implemented the getter on the `Playlist` class. Let me know if you have any questions
