### ISSUE TITLE
XMLHttpRequest error.

### ISSUE THREAD

**Issue by aurinosalvador** [Hexer10/youtube_explode_dart#170]
**Describe the bug**
Error when request video details.

**To Reproduce**
```dart
YoutubeExplode yt = YoutubeExplode();
Video video = await yt.videos.get('https://www.youtube.com/watch?v=jQFC9N5a4FU');
print(video.title);
yt.close();
```

**Stacktrace**
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 908:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 160:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 593:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1232:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 330:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 335:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37332:58                              <fn>

**Enviroment:**
 - Enviroment: Flutter
 - Version 2.4.0-4.1.pre
 - YoutubeExplode Version ^1.10.6

**Comment by 89z** [comment]
Thats a DASH manifest video, so it might not be supported by this package.

**Comment by aurinosalvador** [comment]
Thank's.

**Comment by Hexer10** [comment]
The issue is not that the video contains a DASH manifest, rather that you are trying to use the library on web which doesn't work due to CORS. See #119
