### ISSUE TITLE
[BUG] Videos in a Playlist don't have a description

### ISSUE THREAD

**Issue by paulsam1016** [Hexer10/youtube_explode_dart#171]
**Describe the bug**
Videos in a Playlist don't have a description.

**To Reproduce**
```
await for (Video video in yt.playlists.getVideos('<playlistID>')) {
      print(video.description));
    }
```

**Stacktrace**
I/flutter (28683): 
I/flutter (28683): 
I/chatty  (28683): uid=10171(com.arambankudyil.shelfley.dev) 1.ui identical 6 lines
I/flutter (28683): 
I/flutter (28683): 

**Enviroment:**
 - Enviroment: Flutter
 - Version 2.6.0-12.0.pre.2
 - YoutubeExplode Version 1.10.6

**Comment by Hexer10** [comment]
This is not a bug when you open a playlist page such as https://www.youtube.com/playlist?list=PLr-IftNTIujSF-8tlGbZBQyGIT6TCF6Yd you can see that YouTube doesn't send any description information.
