### ISSUE TITLE
Why muxed has limited quality and can't go beyond 720p30?

### ISSUE THREAD

**Issue by RomjanHossain** [Hexer10/youtube_explode_dart#173]

**Comment by 89z** [comment]
Thats just a limitation of the platform (YouTube). The best quality is only available in the separate streams, its been that way for years, and will only change if YouTube decide to offer more formats.

**Comment by RomjanHossain** [comment]
Then, what's the best  way to download full video from YouTube with the highest quality available?

**Comment by 89z** [comment]
What youre asking is not advisable in the general case, and YouTube many times offers higher quality than can even be displayed on some equipment.

**Comment by Hexer10** [comment]
As @89z already said, youtube doesn't offer muxed streams in the highest quality available. 
If you want to get both audio and video you should download each stream separately and then merge them with a tool like ffpmeg.

**Comment by 89z** [comment]
> If you want to get both audio and video you should download each stream separately and then merge them with a tool like ffpmeg

I see this advice many times, and I just wanted to add - if its just something you want to watch once or twice, you dont even need to merge them. Players likes MPC-HC will play the audio automatically when you start the video, if they have the same name.
