### ISSUE TITLE
Muxed Highest Bitrate getting low quality

### ISSUE THREAD

**Issue by shinewanna** [Hexer10/youtube_explode_dart#186]
In youtube_explode_dart: 1.10.8, it's fine, the bitrate is high, in this version, download speed is really slow.

After upgrade to  youtube_explode_dart: 1.10.9+1, the muxed bitrate is very low quality, but the download speed is good now.

`manifest.muxed.withHighestBitrate()`

**Comment by itssidhere** [comment]
That's a tradeoff between speed and quality

**Comment by Hexer10** [comment]
As @itssidhere said, since we switch to the `ANDROID` client, (before we were using `WEB`) there might be less streams available, but at least the download speed is decent. If you need high quality videos I suggest you to download don't use `muxed` streams.
