### ISSUE TITLE
Update library to YoutubeExplode v5.0.5

### ISSUE THREAD

**Issue by Hexer10** [Hexer10/youtube_explode_dart#19]
A new version of YoutubeExplode for C# was released, I'm starting to updating this, it might require breaking changes.

**Comment by Tizoner27** [comment]
There is already passed more than a month with zero commits done.
Why?
Is this library now dead?
I can't extract most of the youtube videos while official YoutubeExplode is way ahead with version v5.0.5.

**Comment by Hexer10** [comment]
I have not been working at this since almost a month now... I don't only this project to work on at the moment... I've started working at this tough but don't expect the update too soon since the library is to be rewritten from scratch

**Comment by Hexer10** [comment]
The main issue tough should be fixed with #24

**Comment by Hexer10** [comment]
Push a beta version: `1.0.0-beta` see the milestone for the missing features

**Comment by Hexer10** [comment]
Version `1.0.0` published
