### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by pesutsoos** [Hexer10/youtube_explode_dart#192]
Hi there,

`explode.channels.getAboutPageByUsername("HooverphonicMusic");`
The code above throws an error:

`
I/flutter (11002): #0      _InitialData.description (package:youtube_explode_dart/src/reverse_engineering/pages/channel_about_page.dart:89:33)
I/flutter (11002): #1      _InitialData.description (package:youtube_explode_dart/src/reverse_engineering/pages/channel_about_page.dart)
I/flutter (11002): #2      ChannelAboutPage.description (package:youtube_explode_dart/src/reverse_engineering/pages/channel_about_page.dart:14:41)
I/flutter (11002): #3      ChannelClient.getAboutPageByUsername (package:youtube_explode_dart/src/channels/channel_client.dart:79:14)
`

Seems like the crash happens for channels without a details section on the about page.

**Comment by prateekmedia** [comment]
Same if the channel doesn't have a country.

**Comment by Hexer10** [comment]
This is fixed v`1.10.10` those properties are now nullable
