### ISSUE TITLE
[BUG] ChannelUploadList nextPage not working

### ISSUE THREAD

**Issue by prateekmedia** [Hexer10/youtube_explode_dart#193]
**Describe the bug**
When using .nextPage on ChannelUploadList it doesn't returns anything, not even null.

**To Reproduce**
```dart
var channelVid = await yt.channels.getUploadsFromPage(channel_id_here);
print(await channelVid.nextPage());
```

**Enviroment: (please complete the following information):**
 - Enviroment: Flutter
 - Version 2.11 pre
 - YoutubeExplode Version Latest git source
**Additional context**
nextPage works for search but not for channel uploads.

**Comment by Hexer10** [comment]
Could you share the channel id that fails? I just tried this:
```
  var channelVid = await yt.channels.getUploadsFromPage('UCEnBXANsKmyj2r9xVyKoDiQ');
  print(await channelVid.nextPage());
```
and the future completed successfully.

**Comment by Hexer10** [comment]
Closed due to inactivity, please reopen if this still happens.
