### ISSUE TITLE
[BUG] Video Quality

### ISSUE THREAD

**Issue by dvird** [Hexer10/youtube_explode_dart#197]
Hi many times the function "bestquality" return the lowest quality.

I tried the opposite like "streams.sortByVideoQuality().first" and it returns better quality.

this is the link "https://youtube.com/shorts/5M0W2us5yFw?feature=share"

**Comment by Hexer10** [comment]
Thanks for the report, seems like there is a typo here, instead of `first` I'm getting `last` video.

https://github.com/Hexer10/youtube_explode_dart/blob/0ce24bf0178571a0fd2706539b8b94db32a7ede3/lib/src/videos/streams/video_stream_info.dart#L39

I'll make sure to fix it in the next version
