### ISSUE TITLE
[BUG] Can't search for channel or playlist

### ISSUE THREAD

**Issue by prateekmedia** [Hexer10/youtube_explode_dart#198]
Original Youtube Explode can search for playlist and channel too but idk how to search other than videos here using this package.

As this package tries to replace youtube explode in dart, this feature is expected, So I am marking this as a bug.

**Comment by Hexer10** [comment]
Since v`1.11.0` this is possibling using `yt.search.searchContent()`, which can return either a Video, Playlist or Channel, see:

https://github.com/Hexer10/youtube_explode_dart/blob/8026eea9b551d12373c3d18ceef6424a03da52a5/test/search_test.dart#L33-L49
