### ISSUE TITLE
Is there a way to get only playlists or channels in the search result?

### ISSUE THREAD

**Issue by ahmetagilkaya** [Hexer10/youtube_explode_dart#20]
I am using the plugin, everything works very well, but I need some filtering features when searching. I want to filter the result by playlist or channel. Is this possible ? 
Thanks.

**Comment by Hexer10** [comment]
I'm sorry, but currently there is no way to get playlists from a search query.

**Comment by Hexer10** [comment]
I'm reopening this since seems like some progress has been done here: https://github.com/Tyrrrz/YoutubeExplode/issues/226

**Comment by Hexer10** [comment]
Done, check `YoutubeExplode().search.queryFromPage('str')`
