### ISSUE TITLE
 Failed to perform an HTTP request to YouTube due to a fatal failure

### ISSUE THREAD

**Issue by Moatamed8** [Hexer10/youtube_explode_dart#204]
My project run in flutter version 2.2.3 
i can't extract closed caption from package ,and cant update my project to last version

**Comment by Moatamed8** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

• No issues found!

**Comment by Hexer10** [comment]
Please fill-in the bug template, and send the code that produces the issue

**Comment by Moatamed8** [comment]
@Hexer10  
var yt = YoutubeExplode();

  var trackManifest = await yt.videos.closedCaptions.getManifest('_QdPW8JrYzQ')

  var trackInfo = manifest.getByLanguage('en'); // Get english caption.
  
  if (trackInfo != null)
  {
     // Get the actual closed caption track.
     var track = await youtube.videos.closedCaptions.get(trackInfo);
      
    // Get the caption displayed at 1:01
    var caption = track.getByTime(Duration(seconds: 61));
    var text = caption?.text; // "And the game was afoot."
  }
This code so what should i do to resolve it

**Comment by Hexer10** [comment]
Sorry for the late reply, I've tried reproducing the issue but the video is not available anymore. If you still experience this issue please reopen.
