### ISSUE TITLE
ClosedCaptionManifest.getByLanguage autoGenerated bug

### ISSUE THREAD

**Issue by RblSb** [Hexer10/youtube_explode_dart#210]
Currently you still getting auto generated captions with `autoGenerated = false`, because `e.isAutoGenerated` is true.
https://github.com/Hexer10/youtube_explode_dart/blob/7ec0098c7fbbfce0bda446bff1145725251d7e3f/lib/src/videos/closed_captions/closed_caption_manifest.dart#L27

**Comment by Hexer10** [comment]
Thanks for reporting, the fix will be release in the next version.
