### ISSUE TITLE
Update freezed_annotation to version 2

### ISSUE THREAD

**Issue by jakub-cosmose** [Hexer10/youtube_explode_dart#213]
Currently the library depends on freezed_annotation ^1.1.0, so using it with an application that uses freezed 2.x is impossible.
The dependency should be updated to the latest version (currently 2.0.3).

**Comment by nikosportolos** [comment]
Packages are updated in #212. 
Could someone merge this PR please? Thanks!

**Comment by Hexer10** [comment]
This was fixed in v`1.12.0`
