### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by terrasuscompany** [Hexer10/youtube_explode_dart#217]
I am using this code and i am gettin below
var manifest = await yt.videos.streamsClient.getManifest('JiaWCah7Nfs' );

It can be some ip block from youtube. I dont know. when i change connection. its working well. 

ERROR:
Unhandled Exception: VideoUnavailableException: Video 'JiaWCah7Nfs' is unavailable
E/flutter (23712): In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
E/flutter (23712): If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
E/flutter (23712): Please report this issue on GitHub in that case.
E/flutter (23712): #0      WatchPage.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/pages/watch_page.dart:137:9)
E/flutter (23712): <asynchronous suspension>
E/flutter (23712): #1      retry (package:youtube_explode_dart/src/retry.dart:18:14)
E/flutter (23712): <asynchronous suspension>
E/flutter (23712): #2      VideoClient._getVideoFromWatchPage (package:youtube_explode_dart/src/videos/video_client.dart:37:21)
E/flutter (23712): <asynchronous suspension>

**Comment by Hexer10** [comment]
I'm afraid I can't fix this if Youtube is blocking the video for your IP.
