### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cosmane** [Hexer10/youtube_explode_dart#226]
**Describe the bug**
error = {HandshakeException} HandshakeException: Handshake error in client (OS Error: \n\tCERTIFICATE_VERIFY_FAILED: self signed certificate in certificate cha
 type = "HandshakeException"
 message = "Handshake error in client"
 osError = {OSError} OS Error: \n\tCERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:359)
  message = "\n\tCERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:359)"
  errorCode = -1

**To Reproduce**
var yt = YoutubeExplode();
yt.videos.streamsClient
        .getManifest(globalVars.mainVideo.videoId)
        .then((streamManifest) { ... }

**Enviroment: (please complete the following information):**
 - Flutter 2.8.1
 - Dart 2.15.1
 - YoutubeExplode Version ^1.11.0

**Comment by Hexer10** [comment]
This seems like it is not caused by the library but from a self signed certificate of yours.
