### ISSUE TITLE
search live video using channel id 

### ISSUE THREAD

**Issue by harryandroiddev** [Hexer10/youtube_explode_dart#227]
For youtube api uses
https://www.googleapis.com/youtube/v3/search?part=snippet&channelId{YOUR_CHANNEL_ID}&eventType=live&type=video&key={YOUR_API_KEY}

is there any way to search through this plugin using filter as eventType to live .

This api show results only if there is some live video going on the channel else it shows no results how can be done using this plugin .

**Comment by Hexer10** [comment]
Sorry for the late reply. You can set a search filter using the search api, for example:
```
  final yt = YoutubeExplode();
  final liveVideos = await yt.search.search('Music', filter: FeatureFilters.live); // Returns only live videos.
```
