### ISSUE TITLE
Error when getting the comments of a video with comments disabled

### ISSUE THREAD

**Issue by pesutsoos** [Hexer10/youtube_explode_dart#229]
**Describe the bug**
Getting comments on a YouTube video where comments are turner off produces a "Null check operator used on a null value" error.

For example the following video has comments turned off:
https://www.youtube.com/watch?v=jtHb94_MLEE

**To Reproduce**
```dart
CommentsList? commentsList = await youtubeExplode.videos.commentsClient.getComments(video);
```

 - Flutter 3.3.7 • channel stable 
 - YoutubeExplode Version ^1.12.2

**Comment by Hexer10** [comment]
Thanks for reporting this is fixed in v`1.12.3`.
