### ISSUE TITLE
Web version not working

### ISSUE THREAD

**Issue by Megamil** [Hexer10/youtube_explode_dart#232]
Is your feature request related to a problem? Please describe.

Currently, my application is facing issues while downloading files in the web version. The "XMLHttpRequest error" is being displayed and I am unable to find a solution for this.

Describe the solution you'd like

I would like the file download functionality to be implemented in the web version of my application and for it to work in the same way as it does on the mobile version. Additionally, I would like an example of how to download files as the dart:io package is not supported on the web version.

Describe alternatives you've considered

I have considered using another package or library to handle file downloads, but I would like to maintain consistency with the mobile version.

How should this be implemented

One possible way to implement this functionality would be to use the dart:html package to make the download request and handle the file in the browser.

**Comment by Hexer10** [comment]
Please check the pinned issue #119 , unfortunately this cannot be implemented in the library due the CORS.
