### ISSUE TITLE
How to stop or cancel ongoing downloads

### ISSUE THREAD

**Issue by harrowmykel** [Hexer10/youtube_explode_dart#244]
**Is your feature request related to a problem? Please describe.**

How can we stop an ongoing stream? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How should this be implemented**
Write here (if you have considered) a way to implement this feature in the current codebase.
**Additional context**

**Comment by Hexer10** [comment]
You need to subscribe to the stream and then cancel the subscription, for example:
```
final sub = yt.videos.streams.get(stream).listen((data) {
    // Process the data
  });

// Somewhere else
sub.cancel(); // <-- Stop the download
```
