### ISSUE TITLE
[BUG] Null Safety Error

### ISSUE THREAD

**Issue by guiima** [Hexer10/youtube_explode_dart#247]
**Describe the bug**
lib/src/reverse_engineerung/pages/wathc_page.dart ln128

var cookies = req.headers['set-cookie']!;

"Error: Unexpected null value.

Flutter version: 3.10.6
Dart version:  3.0.6

**Comment by Hexer10** [comment]
I can probably ignore the cookies if they are not sent recieved, but this should not happen, on which enviroment were you running the code?
