### ISSUE TITLE
[BUG] Very low Quality videos in muxed

### ISSUE THREAD

**Issue by sergioisair** [Hexer10/youtube_explode_dart#252]
Is it normal that in muxed mode (audio+video), in some videos it only gives me very low qualities? even though the original video is in full hd?
It only happens un some videos

**To Reproduce**
```dart
String id = "baLQkpVEabI";
  var yt = YoutubeExplode();
  var streamManifest = await yt.videos.streamsClient.getManifest(id);
  return streamManifest.muxed.withHighestBitrate().url.toString();
```

 - Enviroment: Flutter
 - Version 3.0.5
 - YoutubeExplode Version 1.12.4

**Comment by Hexer10** [comment]
This is a documented behavior:
https://github.com/Hexer10/youtube_explode_dart/blob/0919e843e979b637c64beaf2bf80fba9b1579b57/README.md?plain=1#L113

Youtube does not provide high quality muxed stream, instead you have to download audio and video separately and then merge them using tools like `ffmpeg`
