### ISSUE TITLE
Getting subtitles doesnt work

### ISSUE THREAD

**Issue by CDrosos** [Hexer10/youtube_explode_dart#257]
Im not sure if im doing something wrong but i cant get subtitles with this code

```
  var yt = YoutubeExplode();

  var trackManifest = await yt.videos.closedCaptions.getManifest('_QdPW8JrYzQ')

  var trackInfo = trackManifest .getByLanguage('en'); // Get english caption.
```
  
While trackManifest has en caption if i check through
` var tracksInfo = trackManifest.tracks; `

if then i run  `trackManifest .getByLanguage('en');` i get nothing

**Comment by Hexer10** [comment]
Do you still have this issue? I cannot reproduce it on my end and now the video is private.

**Comment by CDrosos** [comment]
i wasnt able to make it work but now i get subtitles from trackManifest.tracks. i dont use .getByLanguage() anymore
