### ISSUE TITLE
[BUG] Highest Quality not work

### ISSUE THREAD

**Issue by michalss** [Hexer10/youtube_explode_dart#258]
Hi
```dart
    final manifest = await yt.videos.streamsClient.getManifest('fRh_vgS2dFE');
    final bestQuality = manifest.muxed.bestQuality;
```

notworking, it wont pick the best quility. How do i pick the best one, your docs is outdated...

**Comment by michalss** [comment]
neither 

```dart
manifest.muxed.withHighestBitrate()
```

works.

**Comment by Hexer10** [comment]
Please have a look at this section: https://github.com/Hexer10/youtube_explode_dart#downloading-a-video-stream  
Muxed streams do not have high quality videos.
