### ISSUE TITLE
How to download member-only videos

### ISSUE THREAD

**Issue by WayneChou1** [Hexer10/youtube_explode_dart#264]
**Describe the bug**
I got an error when trying to download the member-only video

> [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: VideoUnplayableException: Video 'mv1ciWnFlPM' is unplayable.
> Streams are not available for this video.
> In most cases, this error indicates that there are 
> some restrictions in place that prevent watching this video.
> Reason: Join this channel from your computer or Android app to get access to members-only content like this video.
> #0      StreamClient._getStreams (package:youtube_explode_dart/src/videos/streams/stream_client.dart:155:7)
> <asynchronous suspension>
> #1      Stream.toList.<anonymous closure> (dart:async/stream.dart:1343:9)
> <asynchronous suspension>

**To Reproduce**
```dart
YoutubeHttpClient client = YoutubeHttpClient();
YoutubeExplode yt = YoutubeExplode(client);
yt.videos.get(url).then((video) {
    Logger().d('download video info:${video.toString()}');
     yt.videos.streamsClient.getManifest(video.id).then((manifest) {
          var stream = manifest.muxed.withHighestBitrate();
          downloadStream(yt, video, StreamType.video,singleStream: stream);
      });
});
```

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - [✓] Flutter (Channel stable, 3.13.9, on macOS 13.5 22G74 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.9 on channel stable at /Users/ls/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (7 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
 - YoutubeExplode Version [e.g. ^2.2.0]

What should I do if want to download a member-only video?

**Comment by WayneChou1** [comment]
Pelase try this url
`https://youtu.be/mv1ciWnFlPM?si=xge5GDca-5jrkTWj`

**Comment by Hexer10** [comment]
If you are not able to view the video from the browser (without being a member of that channel), there is no way the library can access it.
