### ISSUE TITLE
[BUG] Can't retrieve 720p quality in any video

### ISSUE THREAD

**Issue by Joseph-Nathan** [Hexer10/youtube_explode_dart#278]
720p quality dropped from 2days .

**Comment by awnigharbia** [comment]
Me too, I tried all versions.

Any solution?

**Comment by shijinthottiyil** [comment]
Me too , In a project I'm not using youtube_explode_dart but an underlying package use this (pod_player) now that player can't stream 720p youtube videos

**Comment by muhamedRadwan** [comment]
any update on this ?

**Comment by Muhammed-Ramadan512** [comment]
Me too,

Any solution?

**Comment by robisaks** [comment]
According to the original repo this is ported from, muxed streams may be going away.

https://github.com/Tyrrrz/YoutubeExplode/issues/797

**Comment by Hexer10** [comment]
Hello, unfortunately I have no control on how youtube provides the muxed streams, you should consider to use the video-only streams (which should always have high quality steams) and merge/syncronize it with the audio-only track.

**Comment by salar-dev** [comment]
> Hello, unfortunately I have no control on how youtube provides the muxed streams, you should consider to use the video-only streams (which should always have high quality steams) and merge/syncronize it with the audio-only track.

How We can merge/syncronize with the audio-only track do you have any Do you have any ideas?
Because when audio and video are played separately, even if they are at the same time, there is a delay in one of them due to the downloading process sometimes or any other reason.

**Comment by OmarYehiaDev** [comment]
> > Hello, unfortunately I have no control on how youtube provides the muxed streams, you should consider to use the video-only streams (which should always have high quality steams) and merge/syncronize it with the audio-only track.
> 
> How We can merge/syncronize with the audio-only track do you have any Do you have any ideas? Because when audio and video are played separately, even if they are at the same time, there is a delay in one of them due to the downloading process sometimes or any other reason.

I agree, especially when you're handling lecture videos in an LMS app for example :"(
