### ISSUE TITLE
got this error today while downloading youtube video

### ISSUE THREAD

**Issue by Khushnu** [Hexer10/youtube_explode_dart#279]
![Screenshot_1719913832](https://github.com/Hexer10/youtube_explode_dart/assets/34332682/e305a414-3e82-4d1c-8954-d843a8750ead)
Download failed: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
I/flutter (17704): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
I/flutter (17704): If this issue persists, please report it on the project's GitHub page.
I/flutter (17704): Request: get https://rr1---sn-o5t5uxa-pncd.googlevideo.com/videoplayback?expire=1719935019&ei=y8uDZqOmDvuIp-oPx5G2qAQ&ip=101.50.108.71&id=o-AKMPjkrHzuQyU1apZecQk0DRodxW7QY8KpcU2Baqq-Ps&itag=133&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=HE&mm=31%2C29&mn=sn-o5t5uxa-pncd%2Csn-hgn7rnls&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=833750&bui=AbKP-1PN-Inm-NyAdIR2bX5khIrCcpY85fcKrgOartxmFaXvnPQFYbvj9WhyVvDI18n9IY2fOdOW75Ax&spc=NO7bAQSld2_1XwrZKF4kITF6ZQlwg0lBFYO7MXGE3doVxGdqgQk8HDUfbJrn&vprv=1&svpuc=1&mime=video%2Fmp4&ns=_g7zIvxB0Gxs9KZunn74O_MQ&rqh=1&gir=yes&clen=10323794&dur=480.166&lmt=1719720204238648

**Comment by lthoedt** [comment]
I get it as well.

**Comment by Khushnu** [comment]
> I get it as well.
> 
> EDIT: It turns out that it was my fault; i got it in unittests for which the httpClient always gives 400 since you need to mock that which i forgot.

can you explain please ?

**Comment by Hexer10** [comment]
Please create a new issue if this still happens.
