### ISSUE TITLE
[BUG] Sign in to confirm you are not a bot

### ISSUE THREAD

**Issue by mamimotu** [Hexer10/youtube_explode_dart#282]
Describe the bug
The app throws a VideoUnplayableException while trying to fetch a video using the YoutubeExplode package. The video stream is unavailable due to restrictions, potentially requiring a user to confirm they're not a bot by signing in.
![](https://github.com/user-attachments/assets/b184d8c1-fbac-4097-87a8-03399acfe8e1)

To Reproduce
Include the code that reproduces this issue.

dart
Copy code
```
// Sample code using YoutubeExplode to fetch video streams
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

void getVideoStream() async {
  var yt = YoutubeExplode();
  var video = await yt.videos.get('zAhlwBdqVM0'); // Example video ID
  var manifest = await yt.videos.streamsClient.getManifest(video.id);

  if (manifest == null) {
    throw Exception('Stream manifest is unavailable');
  }

  var streamInfo = manifest.audioOnly.first;
  var stream = yt.videos.streamsClient.get(streamInfo);
  print('Stream fetched');
}
```

Stacktrace

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError  
VideoUnplayableException: Video 'zAhlwBdqVM0' is unplayable. Streams are not available for this video.  
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.  
Reason: Sign in to confirm you’re not a bot.

StreamClient._getStreams (stream_client.dart:155)
```

Environment: (please complete the following information):

Environment: [Flutter, Dart VM]
Flutter version: [e.g., 2.8.4]
YoutubeExplode version: [e.g., ^2.5.0]
Additional context
The issue seems to occur due to restrictions placed on certain videos that may require user interaction or sign-in to confirm that they are not automated requests.

**Comment by gmstyle** [comment]
same issue for me:
`[log] Error getting streaming url: VideoUnplayableException: Video 'g72lgml-bIE' is unplayable.
      Streams are not available for this video.
      In most cases, this error indicates that there are 
      some restrictions in place that prevent watching this video.
      Reason: Sign in to confirm you’re not a bot`

**Comment by meetalif** [comment]
Same issue with me. Have you got any solutions?

**Comment by imnadev** [comment]
I am having the same issue. Apparently, Youtube introduced some changes recently. They are blocking IPs/IP ranges which they find to abuse their systems. This issue is affecting all Youtube clients, players and downloaders including the official Youtube apps and websites when logged out.

The easiest way to reproduce this is to connect to free VPN clients because they are highly likely to have their IPs blcoked by YouTube.

Some tools are overcoming this issue by [Supporting OAuth2 Account Integration](https://github.com/lavalink-devs/youtube-source/pull/33#issue-2404447241).

**Comment by nerddude24** [comment]
Can confirm the same problem here, when i try to download some videos i get a 403 error and sometimes it's VideoUnplayableException saying that i must log in.

**Comment by Hexer10** [comment]
I've made some changes on how requests are sent to the yt api and also implemented some other clients (mainly ios), does this still happen? Also in a few days a new version should also support signature deciphering for more complex clients

**Comment by mamimotu** [comment]
I will update soon. great job. do you think you will be able to add youtube-dl support https://github.com/ytdl-org/youtube-dl ?
So it support more platforms like reels and tiktok?

**Comment by Hexer10** [comment]
No, the aim of the project is to support YouTube only
