### ISSUE TITLE
[BUG] VideoUnavailableException

### ISSUE THREAD

**Issue by mamimotu** [Hexer10/youtube_explode_dart#283]
**Describe the bug**
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
VideoUnavailableException: Video 'mk35dZiN8gM' is unavailable In most cases, this error indicates that the video doesn't exist, is private, or has been taken down. If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library. Please report this issue on GitHub in that case.
https://youtube.com/shorts/mk35dZiN8gM?si=5a_SSeyfHktQJfY3
arrow_right

**To Reproduce**
https://youtube.com/shorts/mk35dZiN8gM?si=5a_SSeyfHktQJfY3
arrow_right

**Stacktrace**
Include here the stacktrace (if applicable). 

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - Version [e.g. 2.8.4]
 - YoutubeExplode Version [e.g. ^2.5.0]
**Additional context**

**Comment by Hexer10** [comment]
If you still have this issue please reopen following the issue template.
