### ISSUE TITLE
[BUG] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: VideoUnavailableException: Video 'Dpp1sIL1m5Q' is unavailable

### ISSUE THREAD

**Issue by wandiaprianto93** [Hexer10/youtube_explode_dart#285]
E/flutter (20848): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: VideoUnavailableException: Video 'Dpp1sIL1m5Q' is unavailable
E/flutter (20848): In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
E/flutter (20848): If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
E/flutter (20848): Please report this issue on GitHub in that case.

**Comment by Joseph-Nathan** [comment]
did you found any solution ?

**Comment by shrutgyan** [comment]
Any Updates on this??

**Comment by Hexer10** [comment]
Please create a new issue *making sure to follow the issue template*, otherwise there is not sufficent information at all the debug the issue.
