### ISSUE TITLE
[BUG] Error fetching video qualities: YoutubeExplodeException: Video xWYhcQv7MV0 returned 403 (stream: 18)

### ISSUE THREAD

**Issue by ssss500** [Hexer10/youtube_explode_dart#286]
### Issue Summary
I am encountering the following error on all videos across more than one application:

Error fetching video qualities: YoutubeExplodeException: Video xWYhcQv7MV0 returned 403 (stream: 18)

Any solution?

**Comment by rwrz** [comment]
Same here.

**Comment by JustPrem** [comment]
Similar issue here, getting the 403 error when fetching StreamManifest from url.

![image](https://github.com/user-attachments/assets/92e0491a-7501-418c-af66-edf15de96d06)

**Comment by bigzhu** [comment]
Same

**Comment by mthanhha** [comment]
I have same issue: "YoutubeExplodeException: Video 5W25uqsucTI returned 403 (stream: 18"
Any solution?

**Comment by bigzhu** [comment]
It looks like YouTube has upgraded its validation mechanism for accessing the googlevideo.com stream URL.

**Comment by MostafaSolimanMO** [comment]
Anything guys?

**Comment by bigzhu** [comment]
> > It looks like YouTube has upgraded its validation mechanism for accessing the googlevideo.com stream URL.
> 
> is there any solution ??

It has been confirmed that YouTube has indeed blocked the vulnerable interface used by youtube_explode_dart. 
I spent an entire morning trying to solve this problem and finally succeeded. 
After a few days of testing, I may submit a PR.

**Comment by galal3336** [comment]
@bigzhu Any quick solution????

**Comment by MostafaSolimanMO** [comment]
Would you please let us know what you did or any quick solution or even let us test your approach? @bigzhu

**Comment by bigzhu** [comment]
> Would you please let us know what you did or any quick solution or even let us test your approach? @bigzhu

https://github.com/Hexer10/youtube_explode_dart/blob/699208f1383b547f661fb495e1b3970ecf290634/lib/src/videos/video_controller.dart#L71-L78

The ANDROID_TESTSUITE and ANDROID clients are no longer usable; they have been blocked by YouTube.

**Comment by jonathanMNg** [comment]
> > Would you please let us know what you did or any quick solution or even let us test your approach? @bigzhu
> 
> https://github.com/Hexer10/youtube_explode_dart/blob/699208f1383b547f661fb495e1b3970ecf290634/lib/src/videos/video_controller.dart#L71-L78
> 
> The ANDROID_TESTSUITE and ANDROID clients are no longer usable; they have been blocked by YouTube.

Thank you!
I changed this from androidTestSuiteClient to androidClient and it works!
![image](https://github.com/user-attachments/assets/c3cc35f1-338c-4dc4-9b3f-ba05464b0daa)

**Comment by bigzhu** [comment]
Use my forked version to temporarily solve this problem:
 https://github.com/bigzhu/youtube_explode_dart
I have doubts about how stable this method is.

**Comment by mthanhha** [comment]
> Use my forked version to temporarily solve this problem: https://github.com/bigzhu/youtube_explode_dart I have doubts about how stable this method is. 
It works for me well.

**Comment by bigzhu** [comment]
> @bigzhu THX I check the api, It works. Could I ask where do you get the new clientName and clientVersion? Is there a reference?

Use this project (https://github.com/zerodytrash/YouTube-Internal-Clients/) to run the scan yourself and obtain the currently available interfaces.
This is what I've just scanned:[working_clients.md](https://github.com/user-attachments/files/17126865/working_clients.md)

**Comment by rsozdance** [comment]
> Use my forked version to temporarily solve this problem: https://github.com/bigzhu/youtube_explode_dart I have doubts about how stable this method is.

This temporary solution works fine with me.

**Comment by Hexer10** [comment]
I've just pushed a new version `2.2.2` which should address this issue implementing the `ANDROID_CREATOR` client, thanks to @bigzhu . 

At the moment I'm not sure which would be the most stable client to implement, for example seems like `yt-dlp` is having success with a combination of `IOS` and `WEB_CREATOR` (which requires sig deciphering not currently implemented in the library).

**Comment by theatifwaheed** [comment]
Hello. I had the same issue.
I just updated the version to 2.2.2 and it was working fine.
@Hexer10  Please close this Issue after replying (if any).

**Comment by 1041harpreet** [comment]
@Hexer10  i updated to version 2.2.2 , it works fine for some videos but this issue still present for most of the videos. could you please verify if it is working fine?

**Comment by rsozdance** [comment]
Hello again, it works with some videos and others have the same error. anyone with any updates?

**Comment by s-b-repo** [comment]
we can see how parabolic downloads it it works still and can download mp3 from youtube maybe we can download it as mp3 and play it as it is being downloaded

**Comment by MasterRuma** [comment]
> 이 문제를 일시적으로 해결하려면 제가 포크한 버전을 사용하세요: https://github.com/bigzhu/youtube_explode_dart 이 방법이 얼마나 안정적인지 의심스럽습니다.

이 방법은 저에게 엄청난 도움이 되었습니다!

**Comment by sondo65** [comment]
> Use my forked version to temporarily solve this problem: https://github.com/bigzhu/youtube_explode_dart I have doubts about how stable this method is.

It works for me too

**Comment by marekhanzlik** [comment]
@ssss500 Can we please reopen?
Getting 403 again as of today. Looks like they changed the mechanism again

```
[2024-10-08 23:01:11.760585]---------------------
YoutubeExplodeException: Video cRkaPdfjzEk returned 403 (stream: 137
#0 StreamClient.getManifest. (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
```

**Comment by galal3336** [comment]
Same here

**Comment by sondo65** [comment]
> @ssss500 Can we please reopen? Getting 403 again as of today. Looks like they changed the mechanism again
> 
> ```
> [2024-10-08 23:01:11.760585]---------------------
> YoutubeExplodeException: Video cRkaPdfjzEk returned 403 (stream: 137
> #0 StreamClient.getManifest. (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
> ```

same issue

**Comment by rsozdance** [comment]
Same issue from Middle East

**Comment by 645h1** [comment]
> @ssss500 Can we please reopen? Getting 403 again as of today. Looks like they changed the mechanism again
> 
> ```
> [2024-10-08 23:01:11.760585]---------------------
> YoutubeExplodeException: Video cRkaPdfjzEk returned 403 (stream: 137
> #0 StreamClient.getManifest. (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
> ```

Same here

**Comment by hagemini** [comment]
> Same issue from Middle East

upgrade to 2.2.3 working for me. Hope to help u

**Comment by rsozdance** [comment]
> > Same issue from Middle East
> 
> upgrade to 2.2.3 working for me. Hope to help u

I am getting a new error now;
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: videoQuality cannot be empty
#0      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:73:9)
#1      PodPlayerController._checkAndWaitTillInitialized (package:pod_player/src/controllers/pod_player_controller.dart:82:11)
<asynchronous suspension>
#2      PodPlayerController.initialise (package:pod_player/src/controllers/pod_player_controller.dart:61:5)
<asynchronous suspension>

**Comment by mkamel44** [comment]
> > Same issue from Middle East
> 
> upgrade to 2.2.3 working for me. Hope to help u

what i have to update to get work ?

**Comment by hagemini** [comment]
> > > Same issue from Middle East
> > 
> > 
> > upgrade to 2.2.3 working for me. Hope to help u
> 
> what i have to update to get work ?

youtube_explode_dart: ^2.2.3

**Comment by mkamel44** [comment]
i added in yaml 
dependency_overrides:
  youtube_explode_dart: ^2.2.3
  
  but still
  pod_player: ^0.2.2
  
  not working

**Comment by secret3579** [comment]
Same issue!

**Comment by sayol** [comment]
> i added in yaml dependency_overrides: youtube_explode_dart: ^2.2.3
> 
> but still pod_player: ^0.2.2
> 
> not working my flutter version 3.19.6 any solution?

@mkamel44 Refer to temprory solution `https://github.com/newtaDev/pod_player/issues/238`
