### ISSUE TITLE
[BUG] YoutubeExplodeException Video returned 403 

### ISSUE THREAD

**Issue by galal3336** [Hexer10/youtube_explode_dart#290]
I'm getting 403 again.. any solution?

[2024-10-08 23:01:11.760585]---------------------
YoutubeExplodeException: Video cRkaPdfjzEk returned 403 (stream: 137
#0 StreamClient.getManifest. (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)

**Comment by sondo65** [comment]
same issue

**Comment by SujitChanda** [comment]
Getting same error! 
YoutubeExplodeException (YoutubeExplodeException: Video SYiSevPMW_w returned 403 (stream: 299)

**Comment by nyanzi-ashraf** [comment]
same issues. I update to 2.2.2 but now the error has come back

**Comment by hagemini** [comment]
I'm getting 403 too. Anyone can help ?

**Comment by shinewanna** [comment]
+1

**Comment by AhmedAlaaGenina** [comment]
Any update?

**Comment by aleynaak** [comment]
I'm having the same problem. I started having it today and I'm having this problem with every video. Is it the same for everyone?

**Comment by sheikhhaziq** [comment]
Update to 2.2.3. It worked for me.

**Comment by aleynaak** [comment]
Yes, updating to 2.2.3 worked for me too.

**Comment by hagemini** [comment]
> Update to 2.2.3. It worked for me.

Yes, worked for me too

**Comment by AhmedAlaaGenina** [comment]
after Updating to 2.2.3. i get  muxed empty 
my code 
```
  final video = await _yt.videos.get(youtubeUrl);
      final manifest = await _yt.videos.streamsClient.getManifest(video.id);
      final muxedStreams = manifest.muxed;
      final muxedUrls = muxedStreams.toList().toSet();
      log("muxedStreams: ${manifest.muxed}");
```
the log is [log] muxedStreams: []
muxedStreams is empty now  ?
Any Help ?

**Comment by Hexer10** [comment]
Please follow the template when filing a new issue, anyways updating to the latest version should help.

> **after Updating to 2.2.3. i get muxed empty** my code
> 
> ```
>   final video = await _yt.videos.get(youtubeUrl);
>       final manifest = await _yt.videos.streamsClient.getManifest(video.id);
>       final muxedStreams = manifest.muxed;
>       final muxedUrls = muxedStreams.toList().toSet();
>       log("muxedStreams: ${manifest.muxed}");
> ```
> 
> **the log is [log] muxedStreams: []** muxedStreams is empty now ? Any Help ?

Unfortunately youtube has been removing all muxed streams, the only solution is to get the video and audio stream separately and then merge them with tools like ffmpeg or play them synchronized.

**Comment by AhmedAlaaGenina** [comment]
> Please follow the template when filing a new issue, anyways updating to the latest version should help.
> 
> > **after Updating to 2.2.3. i get muxed empty** my code
> > ```
> >   final video = await _yt.videos.get(youtubeUrl);
> >       final manifest = await _yt.videos.streamsClient.getManifest(video.id);
> >       final muxedStreams = manifest.muxed;
> >       final muxedUrls = muxedStreams.toList().toSet();
> >       log("muxedStreams: ${manifest.muxed}");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **the log is [log] muxedStreams: []** muxedStreams is empty now ? Any Help ?
> 
> Unfortunately youtube has been removing all muxed streams, the only solution is to get the video and audio stream separately and then merge them with tools like ffmpeg or play them synchronized.

but how can i play them synchronized ? any help

**Comment by DharmeshKanjariya** [comment]
> **after Updating to 2.2.3. i get muxed empty**

getting same issue after updating latest version, any solution?

**Comment by basemkhirat** [comment]
Same issue. still returning 403

**Comment by secret3579** [comment]
Same issue! Please update!
