### ISSUE TITLE
[BUG] there are no muxed streams there is only video and only audio  ,why previous version of lib not work ? our apps was stoped please we need stable version

### ISSUE THREAD

**Issue by BetacodeMohammedkhateb** [Hexer10/youtube_explode_dart#292]
**Describe the bug**
there are no muxed streams there are only video and only audio  ,why previous version of lib not work ? our apps was stoped please we need stable version

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart

```

**Stacktrace**
Include here the stacktrace (if applicable). 

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - Version [e.g. 2.8.4]
 - YoutubeExplode Version [e.g. ^2.5.0]
**Additional context**

**Comment by ijashuzain** [comment]
This is happened because Youtube is depreciated muxed streams. Now they only providing AudioOnly and VideoOnly streams.

**Comment by ijashuzain** [comment]
I have developed a simple youtube player by fixing this youtube explode issue with muxed stream deperication (Not including all featured this player have) you can check it and i am welcoming contributions to make it better.

https://pub.dev/packages/y_player

**Comment by ayahsujana** [comment]
> I have developed a simple youtube player by fixing this youtube explode issue with muxed stream deperication. you can check it and i am welcoming contributions to make it better.
> 
> https://pub.dev/packages/y_player

Thank you, i'll try it now. this player has fiture when video has been finish and have callback i need to play another video.

**Comment by Purehi** [comment]
**Changed this. It's working for me.**

`Stream<StreamInfo> _getStreams(VideoId videoId,
      {required bool fullManifest}) async* {
    try {
 
      if (fullManifest) {
        await for (final stream
            in _getStream(videoId, VideoController.androidClient)) {
          yield stream;
        }
      }else{
        // Use await for instead of yield* to catch exceptions
        await for (final stream
        in _getStream(videoId, VideoController.iosClient)) {
          yield stream;
        }
      }
    } on VideoUnplayableException catch (e) {
      if (e is VideoRequiresPurchaseException) {
        rethrow;
      }
      yield* _getCipherStream(videoId);
    }
  }
`

**How to use**
final manifest =
            await yt.videos.streamsClient.getManifest(youtubeIdOrUrl, fullManifest: true);

I have updated my app, you can check it out.
[WeTube:Video&Music](https://play.google.com/store/apps/details?id=free.mor.mordo.do)

**Comment by GdevSP** [comment]
> **Changed this. It's working for me.**
> 
> `Stream _getStreams(VideoId videoId, {required bool fullManifest}) async* { try {
> 
> ```
>   if (fullManifest) {
>     await for (final stream
>         in _getStream(videoId, VideoController.androidClient)) {
>       yield stream;
>     }
>   }else{
>     // Use await for instead of yield* to catch exceptions
>     await for (final stream
>     in _getStream(videoId, VideoController.iosClient)) {
>       yield stream;
>     }
>   }
> } on VideoUnplayableException catch (e) {
>   if (e is VideoRequiresPurchaseException) {
>     rethrow;
>   }
>   yield* _getCipherStream(videoId);
> }
> ```
> 
> } `
> 
> **How to use** final manifest = await yt.videos.streamsClient.getManifest(youtubeIdOrUrl, fullManifest: true);
> 
> I have updated my app, you can check it out. [WeTube:Video&Music](https://play.google.com/store/apps/details?id=free.mor.mordo.do)

It works for me too! Thanks  @Purehi  👏👏👏

**Comment by anilslabs** [comment]
@Purehi @GdevSP 
Thanks for the solution. It worked for me with most YouTube videos but failed for some. 

Following are some of the YouTube video URLs that are not working for me. I am not getting the muxed streams for these URls and also the `getManifest(youtubeIdOrUrl, fullManifest: true)` function is taking so long to return the Stream Manifest data.

1. [https://www.youtube.com/watch?v=ntJ-Q6EXpJA](https://www.youtube.com/watch?v=ntJ-Q6EXpJA)
2. [https://youtu.be/GgnOz8d82aI](https://youtu.be/GgnOz8d82aI)

**Comment by BetacodeMohammedkhateb** [comment]
> I have developed a simple youtube player by fixing this youtube explode issue with muxed stream deperication. you can check it and i am welcoming contributions to make it better.
> 
> https://pub.dev/packages/y_player

thank you pro put how to download video using this lib ?  after update i cant download video with audio please answer and help pro
