### ISSUE TITLE
Getting 403 in muxed | using android client

### ISSUE THREAD

**Issue by HKTareen** [Hexer10/youtube_explode_dart#294]
**Describe the bug**
getting 403 error after using the android client in muxed
**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart

```

**Stacktrace**
(https://rr1---sn-2uja-3ipy.googlevideo.com/videoplayback?expire=1728671909&ei=RBwJZ-L-O9KZhcIPrMy28Aw&ip=119.154.156.227&id=o-AJzj9IqrfBw5l2DpA5gluq6gWL1mxiSj1ypu7XLhG0Ua&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728650308%2C&mh=UX&mm=31%2C29&mn=sn-2uja-3ipy%2Csn-4wg7lnel&ms=au%2Crdu&mv=m&mvi=1&pl=22&rms=au%2Cau&initcwndbps=385000&spc=54MbxQ3dx-wqBzQFZQG7ZmJPXfXd68uD1bCtkSpBJU8Q5PI&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=12368600&ratebypass=yes&dur=215.202&lmt=1706516684438585&mt=1728649977&fvip=3&fexp=51286683%2C51300760&c=ANDROID&txp=5319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgFcCPqGiRI4JOxduuc4iQsKizBvsjhy5HdP7ItxkvQYECIGwu06Ez5ynd7w0rYUTmOO3dU-jxR7PpL4R7jkhI_wFe&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRgIhAO9k7sjlzZBsZie3QmD_fMlheQ8sUkWWDLA5lFgh9PBqAiEAugM6wk6Rj258GGPXVQo6tOaATLutj_5R0bsn2xXyD)

**Enviroment: iOS Simulator:**
 - Enviroment: [3.19 6 ]
 - YoutubeExplode Version 2.3.0+1
**Additional context**

**Comment by Hexer10** [comment]
Hi @HKTareen , the markdown doesn't include any code, also can you trying settings the `ytClients` parameter of `getManifest` to `[YoutubeApiClient.mediaConnect]` or if that doesn't work try with `YoutubeApiClient.androidMusic` and use a music video

**Comment by HKTareen** [comment]
Its working fine now am not getting any 403

**Comment by HKTareen** [comment]
manifest = await yt.videos.streamsClient
        .getManifest(getYouTubeVideoId(widget.url),ytClients: [YoutubeApiClient.android]);
        
        
        i did this to get it done.
