### ISSUE TITLE
[BUG] Muxed video stream is muted

### ISSUE THREAD

**Issue by thinhtran122000** [Hexer10/youtube_explode_dart#300]

**Comment by Hexer10** [comment]
Please reopen following the issue template and including the video id and which stream is affected.

**Comment by thinhtran122000** [comment]
The videoId is " _NlrphuZEoU" and video stream is "https://rr6---sn-8qj-nbo66.googlevideo.com/videoplayback?expire=1729301936&ei=ULkSZ_i4O7mV1d8Pm9jxiAc&ip=14.191.223.141&id=o-ABvY7z1PfDOjxuXSEwkZgSiP_BRQoQUyJsw8AifWsAbW&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&spc=54MbxQpuzKqEjaqfMG7zcxpS5TADBqxLXfFJVnTQ8geaWhfUtw&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&cnr=14&ratebypass=yes&dur=39.450&lmt=1650211877577679&fexp=24350675,24350705,51312688&c=ANDROID&txp=5430434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAN94VqwaBTKL5hd7Ocz7X6fqikbbI9ATPIyQZFoIwm9pAiAQUbnLi3k6pU0dAEK08WPJAy0ttWetZUiyX6iF4abL_w%3D%3D&redirect_counter=1&rm=sn-8qj-nbo6r7e&rrc=79&req_id=942a401403ffa3ee&cms_redirect=yes&cmsv=e&met=1729280341,&mh=pk&mm=29&mn=sn-8qj-nbo66&ms=rdu&mt=1729279978&mv=m&mvi=6&pcm2cms=yes&pl=23&rms=rdu,au&lsparams=met,mh,mm,mn,ms,mv,mvi,pcm2cms,pl,rms&lsig=ACJ0pHgwRgIhALo8Xuw69ef9hgN4PCiPt0Yy6kSCqwQxFR-111DVAylJAiEA2i1cPPSxUArUGIy-bRUiE_hCkGqpcu1R31aszk_vKn4%3D" . When i get it from muxed and play to video_player, it just has video only, it doesn't play with sound.

**Comment by Hexer10** [comment]
@thinhtran122000 have you tried opening that link in a browser? You can hear that there is a sound

**Comment by thinhtran122000** [comment]
@Hexer10 I already test it on browser and it contains sound. But when i play in video_player package, the sound is missing. Yesterday i play it on video_player in the same way that i tell you above, it still have audio. Did i do something wrong or get wrong stream type ? After update, i update my code like this: 

 final controllers = await Future.wait(
      videoIds.map<Future<Uri>>((e) async {
        final manifest = await youtubeExplode.videos.streams.getManifest(
          fullManifest: true, //deprecated
          e,
          ytClients: [
            YoutubeApiClient.android,
          ],
        );

        final url = manifest.muxed.first.url;
        log('$url');
        return url;
      }).toList(),
    );
    youtubeExplode.close();

**Comment by thinhtran122000** [comment]
I figure it out. My emulator is missing sound when i try play video on Youtube app. Thank you for support me @Hexer10
