### ISSUE TITLE
muxed will get empty on youtube video

### ISSUE THREAD

**Issue by this-sunil** [Hexer10/youtube_explode_dart#303]
fetchData() async{
    final yt=YoutubeExplode();
    final manifest = await yt.videos.streamsClient.getManifest("https://www.youtube.com/watch?v=IMLLUfpUb3s");
      print("Manifest ${manifest.muxed.map((e)=>e).toList()}");
  }
video quality can get empty all thing check

**Comment by this-sunil** [comment]
https://rr8---sn-gwpa-o5bee.googlevideo.com/videoplayback?expire=1729362113&ei=YaQTZ7nqJ5SY9fwPrJLK-Aw&ip=152.59.6.232&id=o-AE2-6UeZk1MJcogdDGKD7356gwDFFICcFuSrL9BYMz6X&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1729340513%2C&mh=f4&mm=31%2C29&mn=sn-gwpa-o5bee%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=8&pl=24&rms=au%2Cau&initcwndbps=427500&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=143203162&dur=1600.366&lmt=1717118973992851&mt=1729339997&fvip=1&keepalive=yes&fexp=51312688&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAJHVZB5GzvjxOIPtIr1DDbQhJxUwhegSuCaaQ_Cv4XzYAiA_s2olvDkrwKEKwg9gbxDNDZXCIUZY0cURJT-OeuT25g%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRgIhALig9W_qbP599h_ujHQ42mTSnvW29M5Wb22cS5jVZj5jAiEA6IIAJLINswdcXv1oeGFKVp9McmapbEuPurQlCXOkMek%3D without sound are gettiing this code 


fetchData() async{
    final yt=YoutubeExplode();
    final manifest = await yt.videos.streamsClient.getManifest("https://www.youtube.com/watch?v=IMLLUfpUb3s");
    var streamInfo = manifest.streams;
      print("Manifest ${manifest.muxed.map((e)=>e.url.toString()).toList()} ${streamInfo[0].url} ${streamInfo[0].qualityLabel.split("p")[0]}");
  }

**Comment by this-sunil** [comment]
Manifest [] https://rr8---sn-gwpa-o5bee.googlevideo.com/videoplayback?expire=1729362113&ei=YaQTZ7nqJ5SY9fwPrJLK-Aw&ip=152.59.6.232&id=o-AE2-6UeZk1MJcogdDGKD7356gwDFFICcFuSrL9BYMz6X&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1729340513%2C&mh=f4&mm=31%2C29&mn=sn-gwpa-o5bee%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=8&pl=24&rms=au%2Cau&initcwndbps=427500&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=143203162&dur=1600.366&lmt=1717118973992851&mt=1729339997&fvip=1&keepalive=yes&fexp=51312688&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAJHVZB5GzvjxOIPtIr1DDbQhJxUwhegSuCaaQ_Cv4XzYAiA_s2olvDkrwKEKwg9gbxDNDZXCIUZY0cURJT-OeuT25g%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRgIhALig9W_qbP599h_ujHQ42mTSnvW29M5Wb22cS5jVZj5jAiEA6IIAJLINswdcXv1oeGFKVp9McmapbEuPurQlCXOkMek%3D 1080

**Comment by Hexer10** [comment]
Please don't open multiple issues for the same problem, and **follow the issue template**, posting the video url is not needed.

To fix your issue try using a different yt client, for example:
```
yt.videos.streams.getManifest(videoId,
  ytClients:
  [YoutubeApiClient.androidVr]
  );
```
