### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cristianpessoamillenium** [Hexer10/youtube_explode_dart#308]
The video is not playing, I get this error in the console:

I/flutter (16179): ===== YOUTUBE API ERROR: Bad state: No element ==========
E/flutter (16179): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (16179): #0      PlayerState._initializeNewPlayer (package:news_pro/core/controllers/video/video_controller.dart:34:56)
E/flutter (16179): <asynchronous suspension>

**Comment by RblSb** [comment]
This happens when you try to get muxed streams and then call something like getHighestBitrate(), because there is always empty list now for videos. Is muxed support dropped?
