### ISSUE TITLE
Bug Report: Error Fetching Video Streams

### ISSUE THREAD

**Issue by ssss500** [Hexer10/youtube_explode_dart#312]
**Describe the bug**

An error occurs when trying to fetch video streams using youtube_explode. The video is unavailable due to restrictions that require both logins. Note that they can work randomly. It can work once every 5 times, for example this is error :

Error fetching video qualities: VideoUnplayableException: Video 'PRPnNf-MoBw' is unplayable.
Streams are not available for this video.
Reason: Please sign in
 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No video qualities found
 
**To Reproduce**
Include the code which doesn't work in the code markdown...
```
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

void fetchVideoStream(String videoId) async {
  var yt = YoutubeExplode();
  try {
    StreamManifest manifest = await yt.videos.streamsClient.getManifest(
      videoId,
      ytClients: [
        YoutubeApiClient.safari,
        YoutubeApiClient.mediaConnect,
      ],
    );
    // Process the manifest as needed
  } catch (e) {
    print('Error fetching video qualities: $e');
  }
}
```
 

**Enviroment:**
 - flutter: 3.24.3  
 - dart :3.5.3
 - YoutubeExplode Version : ^2.3.5

**Comment by Hexer10** [comment]
Hi, unfortunately youtube lately has been limiting most clients, could you try adding  `YoutubeApiClient.tv` and check if it helps?

**Comment by ssss500** [comment]
Yes, it works and shows only 360 quality.

This is nice as a temporary solution.

Can we get a quality like 1080, for example, as before, soon?

Or should I look for a different way? Do you suggest an alternative solution that helps me upload a large number of videos and is free?
