### ISSUE TITLE
[Bug]: Stream manifest does not return any muxed streams

### ISSUE THREAD

**Issue by GPSxtreme** [Hexer10/youtube_explode_dart#319]
### What happened?

- muxed streams are not being returned for any video
- video only streams and audio only streams work though

### Package (youtube_explode_dart) version

2.3.6

### Checklist

- [X] I have provided a descriptive title
- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [X] I have tested with the latest version of the library
- [ ] (If relevant) I can open the video/playlist in a incognito/private window without being logged in.
- [ ] I have sponsored the project

**Comment by APPXOTICA** [comment]
Muxed streams are deprecated by YouTube and are not guaranteed to be available for every video. Please [read this](https://github.com/Tyrrrz/YoutubeExplode).
