### ISSUE TITLE
[Bug]: UnimplementedError: Unknown unary operator: typeof

### ISSUE THREAD

**Issue by robelandro** [Hexer10/youtube_explode_dart#320]
### What happened?

the line of code the trigger the issue

```dart
var streamManifest = await yt.videos.streams.getManifest(url);
```

it throws 

`UnimplementedError: Unknown unary operator: typeof`

> this error doesn't occur always.

### Stacktrace / error logs.

```shell
UnimplementedError: Unknown unary operator: typeof
```

### Package (youtube_explode_dart) version

2.3.6

### Checklist

- [X] I have provided a descriptive title
- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [X] I have tested with the latest version of the library
- [ ] (If relevant) I can open the video/playlist in a incognito/private window without being logged in.
- [ ] I have sponsored the project

**Comment by shinewanna** [comment]
It is closed, I still facing the issue.

**Comment by shinewanna** [comment]
Any update? I am still facing this issue.
