### ISSUE TITLE
[Bug]: videos streams are not playing

### ISSUE THREAD

**Issue by anandssm** [Hexer10/youtube_explode_dart#322]
### What happened?

i'm getting same errors for all videos.
other yt client apps with youtube_explode_dart are also not playing videos.

### Stacktrace / error logs.

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: VideoUnavailableException: Video 's-87X3VCFO4' is unavailable
In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
```

### Package (youtube_explode_dart) version

2.3.6

### Checklist

- [X] I have provided a descriptive title
- [X] I have searched the issues of this repository and believe that this is not a duplicate
- [X] I have tested with the latest version of the library
- [ ] (If relevant) I can open the video/playlist in a incognito/private window without being logged in.
- [ ] I have sponsored the project

**Comment by ExoticNx** [comment]
Did you fix this somehow? I am getting same thing.
