### ISSUE TITLE
Unhandled Exception: type 'VideoUnplayableException' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by aleexbt** [Hexer10/youtube_explode_dart#34]
After updating to 1.0.0 and adjusting my code, i'm not able to get video HLS stream URL using the new getHttpLiveStreamUrl. When using hlsLiveStreamUrl on 0.0.17, in the same video, it works without any problem.

**Comment by Hexer10** [comment]
Could you send your code?

**Comment by aleexbt** [comment]
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

final yt = YoutubeExplode();

Future getVideoStream(id) async {
VideoId videoId = VideoId(id);
var video = await yt.videos.streamsClient.getHttpLiveStreamUrl(videoId);
return video; // At this point, isn't it supposed to return the HLS stream url?
}

**Comment by Hexer10** [comment]
I couldn't reproduce this, here is working properly, try to send me also the YouTube link.
I suppose you are able to open the live stream in the browser
