### ISSUE TITLE
[Inquiry] - How to download YouTube video in Flutter

### ISSUE THREAD

**Issue by eric-sison** [Hexer10/youtube_explode_dart#35]
Is there a way to download youtube video in flutter? The example given was downloading a youtube video on a Windows machine.

**Comment by Hexer10** [comment]
Yes, you can download a video using the same way as the example, but if you need a flutter example I could make it

**Comment by eric-sison** [comment]
Yes, that would be great! Thanks! :)

**Comment by Hexer10** [comment]
Example added in `example/video_download_flutter/`:  https://github.com/Hexer10/youtube_explode_dart/blob/master/example/video_download_flutter/lib/main.dart#L56-L112
Feel free to reply here or contact me if something is unclear.

**Comment by Klairm** [comment]
hello, that example is now outdated rigth? Because download_path_provider is legacy, how can I then download then? Also which way could I download just the audio?
