### ISSUE TITLE
Does viewing from this package increase the youtube video's view count?

### ISSUE THREAD

**Issue by kamathprasad9** [Hexer10/youtube_explode_dart#38]
I just wanted to confirm if someone using this package, watches any video, will it automatically increase the view count? Will it be considered as a view

**Comment by Hexer10** [comment]
So, the library fetches the view count directly from the YouTube page, so it will update as soon as the video count on YouTube is updated.
If someone watches a video the view count might not be updated right away for different reasons.
More info here:
https://support.google.com/youtube/answer/2991785?hl=en
https://qr.ae/pNKAxb

**Comment by kamathprasad9** [comment]
I guess there's been some misunderstanding. Im only asking that, if i integrate this plugin in my app, and some person watches some video throught this app, will "that view" be taken in as "a legitimate view". I am asking this because one of the plugins on the pub.dev was using iframes, because of which even if someone plays the video, it will not be counted as a view. Are you understanding now what im asking?

**Comment by Hexer10** [comment]
Yeah sorry, actually I should test it...
Btw by watching do you mean downloading the video stream and playing it on the phone?
