### ISSUE TITLE
[BUG] Unhandled HttpException when downloading

### ISSUE THREAD

**Issue by mymikemiller** [Hexer10/youtube_explode_dart#44]
**Describe the bug**
I often get an HttpException when downloading videos. Because the exception occurs inside the library's code, my only recourse is to restart the download from the beginning every time the error occurs.

**To Reproduce**
```yaml
dependencies:
  youtube_explode_dart: ^1.3.0
```
```dart
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as yt_explode;
final _yt = yt_explode.YoutubeExplode();
var manifest = await _yt.videos.streamsClient.getManifest('Nt6h2EKQE68');
var videoStreamInfo = manifest.muxed.firstWhere((streamInfo) => streamInfo.container == yt_explode.Container.mp4);
var output = file.openWrite(mode: FileMode.writeOnlyAppend);

var success = false;
while (success == false) {
    try {
        final stream = _yt.videos.streamsClient.get(videoStreamInfo);
        await for (var data in stream) {
            output.add(data);
        }
        success = true;
    } catch (e) {
        // We sometimes get the following error from the youtube_explode
        // library, which I'm not sure how to overcome so we just restart the
        // download and hope for the best the next time.
        //
        // _TypeError (type '(HttpException) => Null' is not a subtype of type
        // '(dynamic) => dynamic')
        //
        // See
        // https://stackoverflow.com/questions/62419270/re-trying-last-item-in-stream-and-continuing-from-there
        
        print(e);
        // Clear the file and start over
        await file.writeAsBytes([]);
        output = file.openWrite(mode: FileMode.writeOnlyAppend);
    }
}
```

**Output**
```=== Clone: Download youtube Video Nt6h2EKQE68 ===
Downloading `Down Under - NSP`:
51% [====================================================>                                                    ]
type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'
48% [=================================================>                                                       ]
type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'
48% [=================================================>                                                       ]
type '(HttpException) => Null' is not a subtype of type '(dynamic) => dynamic'
42% [===========================================>                                                             ]
```

**Stacktrace**
The error looks like it's happening [here](https://github.com/Hexer10/youtube_explode_dart/blob/master/lib/src/reverse_engineering/youtube_http_client.dart#L92). Of course I can't edit this code, but some retry logic around the individual http requests could potentially workaround the issue without requiring me to discard all the data I've already downloaded. With the particular run shown above, it was happening around halfway through the download attempts each time, but it often happens at random times; I haven't noticed any discernible pattern.

**Enviroment: (please complete the following information):**
 - Enviroment: Dart VM (server app)
 - Version 2.8.2 (stable)

**Comment by Hexer10** [comment]
Thanks filing a very detailed issue, but unfortunately at the moment I'm not exactly sure why this happens.
Basically, the download is split in many requests of ~10MB, so you would just need to download from the part from where the error was thrown without discarding the rest.
I could catch the exception and resume from where was needed, but I'd like to understand why the exception is thrown in the first place.
I will investigate further into this for sure.

**Comment by mymikemiller** [comment]
I don't think I can "download from the part where the error was thrown" without editing your library, right?

**Comment by Hexer10** [comment]
Unfortunately you're right you need to edit the library code...
I've already done this feature tough, which if everything is alright will be pushed later today or by tomorrow.

It's works by handling an exception thrown while making the requests to YouTube, if an exception is thrown, after 500ms, the request will be sent again beginning from the last downloaded byte. 
If an exception is thrown 5 times on the same request the exception will be thrown anyway.

**Comment by mymikemiller** [comment]
That is great - I’ll put your change through its paces for sure! Until the underlying issue can be fixed, of course :P

**Comment by Hexer10** [comment]
Pushed version `1.3.3` which implements the error handler, let me know if it solves the issue.
