### ISSUE TITLE
How to change the quality of the iPhone

### ISSUE THREAD

**Issue by kindkmj** [Hexer10/youtube_explode_dart#46]
I'm downloading the video using that source, and the iPhone always uses Muxed Stream to get the video, so I can't change the image quality.
How can I change it?

**Comment by Hexer10** [comment]
I'm sorry but I don't understand what do you want to achieve, could you send me your current code and what do you want at the end?

**Comment by kindkmj** [comment]
yt.videos.streamsClient.getManifest(youtubeVideoId).then((manifest) {
      yt.close();

      Iterable<yta.VideoStreamInfo> muxedData = manifest.muxed;
      Iterable<yta.VideoStreamInfo> videoData = manifest.video;
      Iterable<yta.AudioStreamInfo> audioData = manifest.audio;



I'm using it according to the way it's shown, and the mainfest contains data such as muxed video audio, but if I use it as an iPhone, I can only use muxed. This data is combined with video and audio, so it doesn't change the quality. How is it used? Or is there another way?

**Comment by Hexer10** [comment]
What do you mean? When you test your app on an iPhone it doesn't fetch any audio or video stream?

**Comment by kindkmj** [comment]
I want to know how to control the video quality on the iPhone.
Is the package possible?

**Comment by MeTubeapp** [comment]
yes you can fetch muxed data in two quality....

this code is same for iphone or android
 Iterable<MuxedStreamInfo> video =
                                    snapshot.data.muxed;
for low quality ----->   url: video
                                                                        .first
                                                                        .url
                                                                        .toString(),
for high quality ---->
 url: video
                                                                        .last
                                                                        .url
                                                                        .toString(),

**Comment by kindkmj** [comment]
Is it possible to play it on the iPhone with a file other than muxed?

**Comment by Hexer10** [comment]
On the iPhone you can play any stream in whatever quality your prefer... This library is not platform dependant, but if you want the best quality, as already said you need to mix the audio and stream only qualities
