### ISSUE TITLE
[BUG] On channels.getUploads: Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by mymikemiller** [Hexer10/youtube_explode_dart#48]
**Describe the bug**
I'm new-ish to Dart so I'm very probably doing something wrong with Streams here, but I figured the following should work, and should re-fetch the stream from the beginning a second time, creating a second list with no problem:

**To Reproduce**
```dart
    final channelId =
        yt_explode.ChannelId.fromString('UC9CuvdOVfMPvKCiwdGKL3cQ');
    final list =
        await _youtubeExplode.channels.getUploads(channelId).toList();
    final list2 =
        await _youtubeExplode.channels.getUploads(channelId).toList();
```

Instead I get this error on the list2 line: `Bad state: Stream has already been listened to.` But shouldn't calling getUploads a second time create an entirely new stream? Why, then, is it complaining that the stream has already been listened to?

**Enviroment: (please complete the following information):**
 - Enviroment: Dart VM
 - Version: 2.8.2 (stable)

**Comment by Hexer10** [comment]
I couldn't reproduce this from your code, indeed the two values are two completely different streams... Could you send the full stacktrace?

Also you don't need to use `ChannelId.fromString(id)`, you can just `ChannelId(id)` which calls `fromString` for you.

**Comment by mymikemiller** [comment]
Oh boy. My fault. I WAS doing something wrong with Streams. It was just my tests that were failing. I was mocking your library with Mockito and returning a Stream generated from a hard coded array of your Video objects. _youtubeExplode in my code above was actually this mocked YoutubeExplode object:

```
final videos = Stream.fromIterable([...]);

when(mockChannelClient
            .getUploads(yt_explode.ChannelId('UC9CuvdOVfMPvKCiwdGKL3cQ')))
        .thenAnswer((realInvocation) =>
            videos);
```

That's the Stream that had already been listened to when I tried making another call to the mocked getUploads function.

I switched to generating a new stream for every getUploads call and all is working now:

```
Stream<yt_explode.Video> generateMockVideoStream() => Stream.fromIterable([...]);

when(mockChannelClient
            .getUploads(yt_explode.ChannelId('UC9CuvdOVfMPvKCiwdGKL3cQ')))
        .thenAnswer((realInvocation) =>
            generateMockVideoStream());
```

Sorry to bother. Ignore me and keep working on this incredibly useful library!
