### ISSUE TITLE
[BUG] Decipher error

### ISSUE THREAD

**Issue by dimityrivanov** [Hexer10/youtube_explode_dart#53]
**Describe the bug**
Can get audio source url correct its return an url that is not playable or the cipher throws exception
This is the url I am trying with and its failing -> https://m.youtube.com/watch?v=cxjvTXo9WWM

**Stacktrace**
Include here the stacktrace (if applicable). 
`E/flutter (23429): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'group' was called on null.
E/flutter (23429): Receiver: null
E/flutter (23429): Tried calling: group(1)
E/flutter (23429): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (23429): #1      PlayerSource._getDeciphererDefinitionBody (package:youtube_explode_dart/src/reverse_engineering/responses/player_source.dart:98:62)
E/flutter (23429): #2      PlayerSource.getCiperOperations (package:youtube_explode_dart/src/reverse_engineering/responses/player_source.dart:47:26)
E/flutter (23429): #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:23)
E/flutter (23429): #4      ListDecipher.decipher (package:youtube_explode_dart/src/extensions/helpers_extension.dart:38:27)
E/flutter (23429): #5      StreamsClient._getManifest (package:youtube_explode_dart/src/videos/streams/streams_client.dart:134:52)
E/flutter (23429): #6      StreamsClient.getManifest (package:youtube_explode_dart/src/videos/streams/streams_client.dart:223:14)
`

**Comment by TevinWang** [comment]
I'm also having the same bug for select audio streams. It seems like the fix from the last commit was overwritten.

**Comment by austinpower1258** [comment]
It seems like it doesn't work for some audio streams- some YouTube stream urls cannot be extracted. This seems to be a recurrent bug, but I'm not sure what the issue is here.

**Comment by Hexer10** [comment]
This is a known issue, it is happening on yt explode for C# as well: https://github.com/Tyrrrz/YoutubeExplode/issues/427

To fix we need to tweak some regexp still gotta pinpoint where the issue is tough

**Comment by mrklintscher** [comment]
Trying to solve!

**Comment by Hexer10** [comment]
Thanks! Any help is appreciated!

**Comment by wackyapps** [comment]
I am also facing this same exact bug.

Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1))

player_source.dart: line: 98

deciphererFuncBody: "var b=Tt(a,!0);return Nt($t(a,b))"

![image](https://user-images.githubusercontent.com/1482426/88824722-28772d80-d1e0-11ea-8ea1-8c3dd1723e13.png)

Im trying this url: https://www.youtube.com/watch?v=N2-HsIYd0Go

**Comment by Hexer10** [comment]
Just published v`1.4.2` which fixes this issue
