### ISSUE TITLE
The README.md file is outdated and wrong

### ISSUE THREAD

**Issue by ikartikgautam** [Hexer10/youtube_explode_dart#55]
**Is your feature request related to a problem? Please describe.**
The README.md file is outdated and does not comply with the actual functions to be used with the library.

**Describe the solution you'd like**
The README.md file needs to be updated according to the latest version, 

**How should this be implemented**
I can contribute to this work as i have successfully implemented this in my device, and know where what modifications are needed. Please assign this to me.
**Additional context**
![image](https://user-images.githubusercontent.com/39825660/89681647-f4ec7f80-d912-11ea-9082-6c8395539bf5.png)
In this image as you can see that the function provided in the readme file is not an actual function of this library.

Thank You !

**Comment by Hexer10** [comment]
I'll update the readme, thank you. For the time being I hope you understood how to achieve something with the library anyways

**Comment by ikartikgautam** [comment]
yup, the library does  the work as intended. Thanks for the valuable library
