### ISSUE TITLE
Unable to open audio stream url on iOS

### ISSUE THREAD

**Issue by austinpower1258** [Hexer10/youtube_explode_dart#56]
It seems to work fine for Android, but iOS seems to not be able to open the generated audio stream url from getManifest(). I could be doing something wrong in my code, so I'm not sure.

**Comment by Hexer10** [comment]
Please try to post the source code, unfortunately I don't have any iOS device to test the library on, but this should be platform independent, also what error so you get?

**Comment by TevinWang** [comment]
We use this library in order to get an audio stream url of a searched video:
```dart
var manifest = await yt.videos.streamsClient.getManifest(p.video.id);
var streams = manifest.audioOnly;
var audio = streams.last.url;
globals.streamPlaylist.add(new MusicStream(audio.toString(), p.video));
```
Then, we use the[ just_audio](https://github.com/ryanheise/just_audio) library to play the stream url:
```dart
var duration = await globals.advancedPlayer.setUrl(url).catchError((error) {
      // catch audio error ex: 404 url, wrong url ...
      print(error);
    });
globals.advancedPlayer.play()
```
According to the just_audio library, it is __**unable**__ to play **DASH** streams on IOS. When we play the youtube audio stream, we simply get a `Cannot open` error from just_audio (on IOS only). **Are the audio streams that we get from this library DASH? If so, is there a way we can change the audio stream type?**

Thanks for your help!

**Comment by Hexer10** [comment]
Unfortunately all the streams that are provided from YouTube are in DASH format, but I'm not aware of any way to convert or play it on iOS...
The only way I can think of is to download the audio and then play it, but indeed if you do so you lose the ability to stream just a part of the audio

**Comment by rubikon-movement** [comment]
Hey try using the [vlc pluggin for flutter](https://pub.dev/packages/flutter_vlc_player). For ios it uses the native MobileVLCkit from videolan. I created a simple swift app using MobileVLCkit  and tried to stream to a youtube stream and it worked. I think it will work with flutter too. Oh and i forget, i was doing some research to play youtube streams on ios and i found out that iOS doesn't support .webm extention at all. so yes VLC is your only solution

**Comment by lain-ke** [comment]
I had the same problem, what I did was to check the platform (Android or iOS) and play de video if it was iOS and play the music-only url if it was Android, I'm also using `just_audio`.

**Comment by austinpower1258** [comment]
> I had the same problem, what I did was to check the platform (Android or iOS) and play de video if it was iOS and play the music-only url if it was Android, I'm also using `just_audio`.

What type of video url are you using? As mentioned from above, iOS does not support .webm extensions at all, so it doesn't seem to work for us.

**Comment by lain-ke** [comment]
Here's my function:
```
Future<String> getLink(String id) async {
  var _yt = YoutubeExplode();
  var _manifest = await _yt.videos.streamsClient.getManifest(id);
  return Platform.isIOS ? _manifest.muxed.withHighestBitrate().url.toString() : _manifest.audioOnly.withHighestBitrate().url.toString();
}
```

**Comment by TevinWang** [comment]
Thanks! I was wondering if you were able to use that muxed url and play it with the `just_audio` flutter package.

**Comment by lain-ke** [comment]
@TevinWang yeah! I use the `just_audio` package with `audio_service` and it works just fine.

**Comment by Hexer10** [comment]
I'm going to close this since there is nothing that could be done on this package to fix this.

**Comment by josereia** [comment]
> Here's my function:
> 
> ```
> Future<String> getLink(String id) async {
>   var _yt = YoutubeExplode();
>   var _manifest = await _yt.videos.streamsClient.getManifest(id);
>   return Platform.isIOS ? _manifest.muxed.withHighestBitrate().url.toString() : _manifest.audioOnly.withHighestBitrate().url.toString();
> }
> ```

That worked perfectly! Thank you very much. 😀😉🫰👍🤝
