### ISSUE TITLE
Web support with cors

### ISSUE THREAD

**Issue by cacianokroth** [Hexer10/youtube_explode_dart#58]
Hello Sir, I'm having this problem:
![image](https://user-images.githubusercontent.com/17991860/90146305-45227200-dd57-11ea-87e6-e91551182112.png)

Do you have any idea of ​​a solution?
Regards.

**Comment by Hexer10** [comment]
Refer to https://github.com/Hexer10/youtube_explode_dart/issues/37 ,
There is no way to make this library work on web without using some kind of server that sits between the client and youtube, which should to something like

Client -> Server (With CORS if on different origin)-> Youtube
