### ISSUE TITLE
 It seems that YouTube has changed its algorithm again

### ISSUE THREAD

**Issue by trighomautumnatg** [Hexer10/youtube_explode_dart#59]
Same issue seems to be happening again like it did the past  time recently. New videos streams can't be found. (At least as far as I've tested.)

**Comment by Hexer10** [comment]
This was already fixed in the original YoutubeExplode repo, when I can  I'll push a fix

**Comment by Hexer10** [comment]
Fixed in v1.4.3 please update

**Comment by trighomautumnatg** [comment]
My hero @Hexer10
