### ISSUE TITLE
How to Search For a Video using your library

### ISSUE THREAD

**Issue by ikartikgautam** [Hexer10/youtube_explode_dart#60]
Hi, I have been searching for an answer for this question from last 2 weeks. tried to decompile your source code tried messaging you on your telegram, but you ignored it, Huhhh ... . Now  am left with no option other than creating an issue about this,  Please tell me how to search a video and get video id of searched Video using your library ? better if i can get response in JSON format

**Comment by Hexer10** [comment]
the search query returns also the video ids, try to use `video.id`

**Comment by ikartikgautam** [comment]
can you please explain with some kind of example ? it will be really helpful

**Comment by Hexer10** [comment]
Something like:
```dart
 var videos = await yt.search 
     .getVideosAsync('undead corporation megalomania') 
     .toList(); 
print(videos[0].title);
```

**Comment by ikartikgautam** [comment]
Thanks brother, finally it worked and i am able to extract the id of videos.
