### ISSUE TITLE
[BUG] Calling getManifest causes app to hang and never exit

### ISSUE THREAD

**Issue by mymikemiller** [Hexer10/youtube_explode_dart#61]
**Describe the bug**
Calling yt.videos.streamsClient.getManifest() causes the app to hang for a very long time before exiting. This happens when the client is handled exactly like in the example code.

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

Future<void> main() async {
  var yt = YoutubeExplode();
  var manifest = await yt.videos.streamsClient.getManifest('bo_efYhYU2A');

  print('Size: ${manifest.video.first.size}');

  // Close the YoutubeExplode's http client.
  yt.close();
}
```

When I run the [example code](https://pub.dev/packages/youtube_explode_dart/example) in vscode, I get the following output
```$ dart bin/main.dart                                                                                                                                          [21:41:19]
Title: Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video)
```
after which the process exits and I'm returned to the terminal. 

When I run the repro code above, I get the following output
```$ dart bin/main.dart
Size: 13.594542503356934 MB
```
but the process never exits and I have to kill the process to get back to the terminal.

**Enviroment:**
 - Enviroment: Dart VM
 - Version [e.g. 2.9.1]

**Comment by Hexer10** [comment]
I could reproduce this, but I'm not sure why the process hangs (only when used getManifest), there shouldn't be any sink left open

**Comment by Hexer10** [comment]
Found it, here I'm using a timer to cache the http requests 
https://github.com/Hexer10/youtube_explode_dart/blob/a56ca657c4a80edd700a4d1294dae6cf009ec45a/lib/src/reverse_engineering/responses/player_source.dart#L116-L118

I should stop the timer if the yt client is closed or cache in another way, which I think is the best idea

**Comment by mymikemiller** [comment]
Nice work! How did you find the culprit so quickly? I've run into this problem before, needing to find left-open http clients or, apparently, unstopped timers. Did you use Observatory or some other tool to let you know the line of code that opened/created the problematic object? Or did you just know what types of things to look for, and scour your whole codebase?

Thanks for looking into this!

**Comment by Hexer10** [comment]
At first glance I tried to use the Observer to find out what was happening but I could get anything useful from it...
Then I checked every function that was called and tried to split the code has much as I could into smaller pieces until I found the code I was looking for.
