### ISSUE TITLE
Is there a way to get high quality videos with audio?

### ISSUE THREAD

**Issue by bdlukaa** [Hexer10/youtube_explode_dart#62]
Whenever I try to download the `muxed` from `manifest`, I only get 360p, but in the youtube player the video can be played with 2016p. Why?

Sorry for the bad english :)

**Comment by rubikon-movement** [comment]
The highest available quality is 720p. Actualy when people upload a video to a server youtube split audio and video and get. To get the highest quality of a video you need to write `manifest.videoOnly.sortByVideoQuality();` : it will return a list of videos. If you want audio you need to play it sync. Hope it will help

**Comment by Hexer10** [comment]
As @rubikon-movement said there is no way to get an high quality video with audio you need either to play the track in sync or merge the twos using some library such as `ffmpeg`.

Note: You can get videos over 720p quality, if the video has the track available.
