### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by SwissCheese5** [Hexer10/youtube_explode_dart#63]
Hello, the _httpClient field in the YoutubeExplode class is private with no way to change it.
I would like access to it to either edit or completely override it. 

This will enable us to set up custom proxies and such.

**Comment by Hexer10** [comment]
Done with https://github.com/Hexer10/youtube_explode_dart/commit/fd88cf09077397f0cc300fd9d24e30e50e5f5ab1

Now you can pass custom http clients like this
```dart
import 'package:http/http.dart' as http;
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

Future<void> main() async {
  var client = MyClient();
  var yt = YoutubeExplode(YoutubeHttpClient(client));
  var video =
      await yt.videos.get('https://www.youtube.com/watch?v=bo_efYhYU2A');

  print('Title: ${video.title}');

  // Close the YoutubeExplode's http client.
  yt.close();
}

class MyClient extends http.BaseClient {
  final _client = http.Client();

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    print('MyClient: $request');
    return _client.send(request);
  }

  @override
  void close() => _client.close();
}

```

Let me know if this works for you, and if not please reopen this issue

**Comment by tinazhe** [comment]
> Done with [fd88cf0](https://github.com/Hexer10/youtube_explode_dart/commit/fd88cf09077397f0cc300fd9d24e30e50e5f5ab1)
> 
> Now you can pass custom http clients like this
> 
> ```dart
> import 'package:http/http.dart' as http;
> import 'package:youtube_explode_dart/youtube_explode_dart.dart';
> 
> Future<void> main() async {
>   var client = MyClient();
>   var yt = YoutubeExplode(YoutubeHttpClient(client));
>   var video =
>       await yt.videos.get('https://www.youtube.com/watch?v=bo_efYhYU2A');
> 
>   print('Title: ${video.title}');
> 
>   // Close the YoutubeExplode's http client.
>   yt.close();
> }
> 
> class MyClient extends http.BaseClient {
>   final _client = http.Client();
> 
>   @override
>   Future<http.StreamedResponse> send(http.BaseRequest request) {
>     print('MyClient: $request');
>     return _client.send(request);
>   }
> 
>   @override
>   void close() => _client.close();
> }
> ```
> 
> Let me know if this works for you, and if not please reopen this issue

I am getting an error from VScode that says:
`The instance member 'client' cant be accessed in an initializer.`
