### ISSUE TITLE
[BUG] Name conflict with flutter/src/widgets/container.dart

### ISSUE THREAD

**Issue by superquartet** [Hexer10/youtube_explode_dart#66]
**Describe the bug**
There is a serious name conflict on 'Container' with flutter/src/widgets/container.dart.
This could be avoided by using a certain prefix, but not a clean way.

**To Reproduce**
```dart
import 'package:flutter/material.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

class Box extends StatelessWidget {
  return Container();
}
```

**Stacktrace**
Include here the stacktrace (if applicable). 
```
The name 'Container' is defined in the libraries 'package:flutter/src/widgets/container.dart' and 'package:youtube_explode_dart/src/videos/streams/container.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```

**Enviroment: (please complete the following information):**
 - Enviroment: Flutter
 - Version 1.21.0-1.0.pre

**Comment by superquartet** [comment]
This problem can be fixed by applying Pull request #65 by hiding Container of youtube_explode_dart.

**Comment by Hexer10** [comment]
I'm not too keen on this since it might cause breaking change for the users who are already using the library.

To avoid this you can import the library using as like this:
```
import 'youtube_explode_dart/youtube_explode_dart` as yt
```

Another solution might be for you to hide manually the library or to create a new file like `youtube_explode_flutter.dart` which exports only the classes which don't conflict with flutter.

Let me know what you think about that

**Comment by superquartet** [comment]
Thank you for your reply.  I understand this change could cause a compatibility issue.

Since 'Container' in flutter/materal is one of the most often-used classes, this fix will be beneficial for most developers and, in my opinion, this benefit surpasses the risk of the compatibility issue. (Because I cannot imagine a case where Container in youtube_explode_dart is directly used.)

I hope this change is applied as default, but if it's difficult, I don't mind using solutions you suggested.

**Comment by Artx-II** [comment]
I personally agree with @superquartet pull request, I would prefer if there is nothing conflicting with the material library and since I use this library I've never found a case where I need to directly use Container from youtube_explode_dart.

**Comment by Hexer10** [comment]
The only use-case I could find was to filter a list against a specific container type.
Just to leave it exported by default I think I'm going to rename the `Container` class to something like `StreamContainer`, `YoutubeContainer` or smth like that

**Comment by superquartet** [comment]
That seems to be the best solution!
Thank you for your consideration.
