### ISSUE TITLE
[BUG] error when retrieve video meta data. 

### ISSUE THREAD

**Issue by desunny** [Hexer10/youtube_explode_dart#67]
I got the some error when connect to retrieve some video meta data from youtube by youtube_explode_dart. Here is error message. I guess it's not bug, may be it's blocked from youtube or the connection url may be changed. 

Please check below error messages. 

E/flutter ( 7562): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FatalFailureException: Failed to perform an HTTP request to YouTube due to a fatal failure.
E/flutter ( 7562): In most cases, this error indicates that YouTube most likely changed something, which broke the library.
E/flutter ( 7562): If this issue persists, please report it on the project's GitHub page.
E/flutter ( 7562): Request: GET https://youtube.com/list_ajax?style=json&action_get_list=1&list=PLb8NUYaYc3RnOFmDF0HE68_F_U72Yn04un&index=0&hl=en
E/flutter ( 7562): Response: (400)
E/flutter ( 7562): 
E/flutter ( 7562): #0      YoutubeHttpClient._validateResponse (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:47:7)
E/flutter ( 7562): #1      YoutubeHttpClient.getString (package:youtube_explode_dart/src/reverse_engineering/youtube_http_client.dart:57:7)
E/flutter ( 7562): <asynchronous suspension>
E/flutter ( 7562): #2      PlaylistResponse.get.<anonymous closure> (package:youtube_explode_dart/src/reverse_engineering/responses/playlist_response.dart:58:34)
E/flutter ( 7562): #3      retry (package:youtube_explode_dart/src/retry.dart:15:28)
E/flutter ( 7562): <asynchronous suspension>
E/flutter ( 7562): #4      PlaylistResponse.get (package:youtube_explode_dart/src/reverse_engineering/responses/playlist_response.dart:57:12)
E/flutter ( 7562): #5      PlaylistClient.getVideos (package:youtube_explode_dart/src/playlists/playlist_client.dart:39:34)
E/flutter ( 7562): <asynchronous suspension>
E/flutter ( 7562): #6      main (package:mind_app_yt/main.dart:69:49)
E/flutter ( 7562): <asynchronous suspension>
E/flutter ( 7562): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter ( 7562): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 7562): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 7562): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 7562): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 7562): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter ( 7562): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 7562): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7562):

**Comment by Hexer10** [comment]
Please send me your code

**Comment by desunny** [comment]
대용량 첨부 파일은 30일간 보관 / 100회까지 다운로드 가능




mind_app_yt_for_debug.zip 261MB


  다운로드 기간: 2020/09/10 ~ 2020/10/10






Hello, 
 
Here is my code.
 
This code is for insert youtube video metadata to the firebase firestore. 
There is no google-services.json file in this attached zip-file. However you can test about retrieve you tube metadata by youtube_explode_dart. 
 
Thanks in advance. 
 
Best Regards. 
 
 
-----Original Message-----

**Comment by Hexer10** [comment]
@desunny  There is no zipfile attached to your reply, please try again

**Comment by desunny** [comment]
Hi, 
 
Here are attached files made by me except other libraries. 
 
Thanks & Regards. 
 
-----Original Message-----

**Comment by Hexer10** [comment]
You can't attach files to the email and reply it to GitHub, you should attach directly from a webpage comment

**Comment by desunny** [comment]
Sorry. Here is my source file. 
[lib.zip](https://github.com/Hexer10/youtube_explode_dart/files/5213991/lib.zip)


Thank you.
