### ISSUE TITLE
publishDate in addition to uploadDate

### ISSUE THREAD

**Issue by mymikemiller** [Hexer10/youtube_explode_dart#68]
**Is your feature request related to a problem? Please describe.**
Videos come back from _youtubeExplode.channels.getUploads() in publish order, not upload order. This is good; it matches what is seen on the channel's video upload page (e.g. https://www.youtube.com/user/GameGrumps/videos)

**Describe the solution you'd like**
Can you expose the *publish* date that matches the order the videos are returned in?

**How should this be implemented**
I'm not sure how the publish date could be scraped from the uploads page. The only "dates" shown are things like "6 hours ago" and "2 months ago."

**Additional context**
My use case: to reduce comparisons, I need to be able to put an arbitrary, random collection of videos into an order that matches what will be returned by your library.

**Comment by mymikemiller** [comment]
PR https://github.com/Hexer10/youtube_explode_dart/pull/74 resolves this by adding publishDate to videos. An additional request for the video page must be made for every video returned, which may be too expensive to consider adding to the library. I couldn't find any other place to retrieve the publishDate, and I could not find any place the publish time was available, just the date (all times are midnight, but the dates are correct)

**Comment by Hexer10** [comment]
I've quite lost the track about this @mymikemiller , do you still need this, or it is solved?
