### ISSUE TITLE
[Feature Request] Channel description

### ISSUE THREAD

**Issue by mymikemiller** [Hexer10/youtube_explode_dart#70]
**Is your feature request related to a problem? Please describe.**
A channel's description is not available through the library.

**Describe the solution you'd like**
The Channel object should make the description available. The full description can be found at https://www.youtube.com/channel/$id/about?hl=en

**Describe alternatives you've considered**

**How should this be implemented**
See https://github.com/Hexer10/youtube_explode_dart/pull/69 for one possible implementation.

**Additional context**
I took a stab at implementing fetching of the channel description in the PR linked above. It works, but since you're more familiar with the site, I figure you might know of a better way to do it. Happy to make changes to the PR if requested.

**Comment by Hexer10** [comment]
Closed with #69
