### ISSUE TITLE
How to retrieve cc-by Creative Commons license video from youtube? 

### ISSUE THREAD

**Issue by desunny** [Hexer10/youtube_explode_dart#72]
I want to get cc-by license video from youtube. Is there any way for checking license when i use this library? 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How should this be implemented**
Write here (if you have considered) a way to implement this feature in the current codebase.
**Additional context**

**Comment by Hexer10** [comment]
Can you send a video example and the data you want to retrieve exactly?

**Comment by desunny** [comment]
Really Thanks. 

네이버 메일 앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Mattia" <notifications@github.com>
받는사람: "Hexer10/youtube_explode_dart" <youtube_explode_dart@noreply.github.com>
참조: "desunny" <desunny@naver.com>,"Author" <author@noreply.github.com>
날짜: 2020.10.02 오전 01:03:56 (GMT+09:00)
제목: Re: [Hexer10/youtube_explode_dart] How to retrieve cc-by Creative Commons license video from youtube? (#72)

Can you send a video example and the data you want to retrieve exactly?

**Comment by Hexer10** [comment]
Closing as no meaningful reply was received .
