### ISSUE TITLE
[BUG] Not able to fetch streamInfo for some videos

### ISSUE THREAD

**Issue by RaghuMudem** [Hexer10/youtube_explode_dart#75]
**Describe the bug**
Hi, I am using this package for my YouTube videos play in my Flutter application. Most of the videos are playing.

I noticed that, this package is not fetching steamInfo for some of the videos like **videoId: FKUvkKsTzV8**. I am using a url from streamInfo to play in my application. When i execute the below code, client program end up with the below mentioned error log. 

**To Reproduce**
Video Id:  **FKUvkKsTzV8**

Code Snippet:
```dart
      var yt = YoutubeExplode();
      var manifest = await yt.videos.streamsClient.getManifest('FKUvkKsTzV8');
      var streamInfo = manifest.muxed.withHighestBitrate();
      print('streamInfo ${streamInfo.url}');
      // Close the YoutubeExplode's http client.
      yt.close();
```

**Stacktrace**
Error Log:

E/flutter (21966): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Unhandled error Instance of 'VideoRequiresPurchaseException' occurred in bloc Instance of 'VideoBloc'.
E/flutter (21966): #0      StreamsClient._getStreamContextFromWatchPage (package:youtube_explode_dart/src/videos/streams/streams_client.dart:90:7)
E/flutter (21966): <asynchronous suspension>
E/flutter (21966): #1      StreamsClient.getManifest (package:youtube_explode_dart/src/videos/streams/streams_client.dart:225:27)
E/flutter (21966): <asynchronous suspension>
E/flutter (21966): #2      VideoBloc.mapEventToState (package:pca_app/services/media/video_bloc.dart:30:52)
E/flutter (21966): <asynchronous suspension>
E/flutter (21966): #3      Bloc._bindEventsToStates.<anonymous closure> (package:bloc/src/bloc.dart:252:20)
E/flutter (21966): #4      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:644:30)
E/flutter (21966): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (21966): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21966): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (21966): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (21966): #9      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (21966): #10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (21966): #11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (21966): #12     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (21966): #13     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (21966): #14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (21966): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (21966): #16     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (21966): #17     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (21966): #18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (21966): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (21966): #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21966): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (21966): 
E/flutter (21966): #0      Bloc.onError.<anonymous closure> (package:bloc/src/bloc.dart:146:7)
E/flutter (21966): #1      Bloc.onError (package:bloc/src/bloc.dart:147:6)
E/flutter (21966): #2      _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (21966): #3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (21966): #4      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
E/flutter (21966): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
E/flutter (21966): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
E/flutter (21966): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
E/flutter (21966): #8      _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:400:20)
E/flutter (21966): #9      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:330:15)
E/flutter (21966): #10     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:399:5)
E/flutter (21966): #11     _BroadcastStreamController._addError (dart:async/broadcast_stream_controller.dart:297:5)
E/flutter (21966): #12     _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (21966): #13     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (21966): #14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
E/flutter (21966): #15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
E/flutter (21966): #16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
E/flutter (21966): #17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
E/flutter (21966): #18     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:132:11)
E/flutter (21966): #19     _ForwardingStream._handleError (dart:async/stream_pipe.dart:97:10)
E/flutter (21966): #20     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
E/flutter (21966): #21     _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (21966): #22     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (21966): #23     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
E/flutter (21966): #24     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
E/flutter (21966): #25     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
E/flutter (21966): #26     _DelayedError.perform (dart:async/stream_impl.dart:622:14)
E/flutter (21966): #27     _StreamImplEvents.handleN

**Additional context**
I copied the video id (FKUvkKsTzV8) and played in windows browser in youtube website. It is playing nice with a label, "preview" at the left bottom side. Given video id is a sample, there are so many videos not playing. Specifically, videos which is posted by "YouYube Movies" are not playing. I didn't understand why the same is not playing in my application using this package.

**Comment by Hexer10** [comment]
I've tried to open the video on my mobile but I couldn't get it working... Do you still can open it?![IMG_20200928_111240.jpg](https://user-images.githubusercontent.com/21113203/94413712-bb4e2d00-017b-11eb-8875-f1adebaa93b8.jpg)

**Comment by RaghuMudem** [comment]
Hi Hexer10,

Thankyou so much for your reply. 

The video can be played from Netherlands region, it is playing fine in my desktop browser. Please check the below attached screen and highlighted texts. But the same is not working with my application build on this package for fetching stream information. 

Any guess some thing, am i missing to fetch video stream? like region parameter while fetching video id? Something like this? 

Working video screen for reference:

![image](https://user-images.githubusercontent.com/42538820/94418806-2dc20b80-0182-11eb-91ec-e7f0e7232dde.png)

**Comment by Hexer10** [comment]
Are you logged in your youtube account? Can you try in incognito?

**Comment by RaghuMudem** [comment]
Hi Hexer10,

It is not only region specific videos. It is also with other videos which movie has buy options. I hope user has to by the video to play but in youtube browser, its is playing a trailer for free. I would like to play the same trailers.

Here is not working video samples:
https://www.youtube.com/watch?v=ZMWjixQbqXY
https://www.youtube.com/watch?v=Zat88Rsxp94
https://www.youtube.com/watch?v=2YQ9W0BP2Gw

**Comment by Hexer10** [comment]
So, every video you sent me is region locked, however I was able to have a look at them with a VPN, what you need to do is to use a try catch around the streamClient to catch the `VideoRequiresPurchaseException` exception and get the streamInfo of that video id, something like this:

```
  StreamManifest manifest;
  try {
    manifest = await yt.videos.streamsClient.getManifest(video.id);
  } on VideoRequiresPurchaseException catch (e) {
    manifest =  await yt.videos.streamsClient.getManifest(e.previewVideoId);
  }
```

btw for same reason BLOC doesn't show the full error message, you should've told you that that video requires a purchase and there is a preview video id available.

**Comment by RaghuMudem** [comment]
Hi Hexer10, 

Thankyou so much for your quick and helpful response. That worked for me.

Sorry, I am thinking that, I have provided the information in additional context section in the question. That was my mistake.

Appreciates your help on this.

**Comment by RaghuMudem** [comment]
Hi Hexer10, 

That was really great help for me to fetch most of the YouTube video stream information. 

Today i noticed some of the videos is still not able to fetch stream information. Package is failing with the below mentioned error logs. 

Here is the youtube videoId's which are failing:

- 96KOJTcxOtU
- sXMqM417GAo
- _eFZM-fQgdA
- 3dJoI6IC8iE
- iznJrXGkFvU

### Error Logs:

I/flutter (23971): **FormatException: Unexpected character (at character 1)
I/flutter (23971): unction() {return (window.yt && yt.config_) || ytcfg.data_ || (ytcfg.data_ ...
I/flutter (23971): ^**
I/flutter (23971): FormatException: Unexpected character (at character 1)
I/flutter (23971): unction() {return (window.yt && yt.config_) || ytcfg.data_ || (ytcfg.data_ ...
I/flutter (23971): ^
I/flutter (23971):  trace #0      VideoBloc._getStreamInfoFromClient (package:pca_app/services/media/video_bloc.dart:81:7)
I/flutter (23971): <asynchronous suspension>
I/flutter (23971): #1      VideoBloc.mapEventToState (package:pca_app/services/media/video_bloc.dart:42:21)
I/flutter (23971): <asynchronous suspension>
I/flutter (23971): #2      Bloc._bindEventsToStates.<anonymous closure> (package:bloc/src/bloc.dart:252:20)
I/flutter (23971): #3      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:644:30)
I/flutter (23971): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter (23971): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (23971): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter (23971): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter (23971): #8      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter (23971): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter (23971): #10     _PendingEven
**I/flutter (23971): _buildPlayerWidget state VideoError { error: FormatException: Unexpected character (at character 1)
I/flutter (23971): unction() {return (window.yt && yt.config_) || ytcfg.data_ || (ytcfg.data_ ...
I/flutter (23971): ^
I/flutter (23971):  }**

**Note:** I am sure most of the videos does not have location restrictions too. And not even purchase required.

**Comment by Hexer10** [comment]
Thanks for raising the issue on the  youtube explode repo I'm going to update this library as well later today
