### ISSUE TITLE
youtube_explode_dart takes 30 seconds to get CC subtitles.

### ISSUE THREAD

**Issue by zxl777** [Hexer10/youtube_explode_dart#81]
youtube_explode_dart takes 30 seconds to get CC subtitles.

It only takes less than 5 seconds to download subtitles with YouTube-DL.
`youtube-dl --write-auto-sub --sub-lang en --skip-download  "https://www.youtube.com/watch?v=NlcBA8s22BA"`

Is there any way to greatly improve the speed of downloading and parsing CC?

**Comment by Hexer10** [comment]
I'm not sure how youtube dl fetches the subtitles, but I can try to checkout how they do so

**Comment by zxl777** [comment]
thanks, now youtube-dl backup here
https://gitlab.com/ytdl-org/youtube-dl

**Comment by Hexer10** [comment]
Closed in v1.7.0
