### ISSUE TITLE
[BUG] Can not get getManifest

### ISSUE THREAD

**Issue by binhbk230** [Hexer10/youtube_explode_dart#83]
**Describe the bug**

I try to use this code:

`var yt = YoutubeExplode();
  var manifest = await yt.videos.streamsClient.getManifest(video.id);`

But it through exception : "NoSuchMethodError: The getter 'js' was called on null.
Receiver: null
Tried calling: js"

Please help to check it

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart

```

**Stacktrace**
Include here the stacktrace (if applicable). 

**Enviroment: (please complete the following information):**
 - Enviroment: [Flutter o Dart VM]
 - Version [e.g. 2.8.4]

**Additional context**

**Comment by Hexer10** [comment]
Which version are you using? This should be fixed in the latest one

**Comment by binhbk230** [comment]
Thanks @Hexer10  for reply, Currently i use 1.6.1 version. I try the latest version is 1.6.2 and issue is fixed. Thank you so much for this great library
