### ISSUE TITLE
[BUG] More English subtitles

### ISSUE THREAD

**Issue by zxl777** [Hexer10/youtube_explode_dart#84]
The function of getting CC has made great progress, we can get CC subtitles in vtt format. Thank you.
But now there are 2 problems:
1.  No argument can be distinguished with English subtitles, I can only see the url.
2. There is no cc subtitle in json format.

```
var yt = YoutubeExplode();
var manifest = await yt.videos.closedCaptions
                      .getManifest('GWGbOjlJDkU', autoGenerated: true);
print(manifest.tracks);
yt.close();
```

![image](https://user-images.githubusercontent.com/816448/99041336-b1ff0f80-25c5-11eb-9e60-0e0b530f247a.png)

**Comment by Hexer10** [comment]
Now you can get the subtitles formatted as json in this way:
```
  var manifest = await yt.videos.closedCaptions
      .getManifest('....');
  var trackInfo = manifest.getByLanguage('en');
  var track = await yt.videos.closedCaptions.get(trackInfo.first);
  print(json.encode(track.toJson()));
```
you should print out a track to understand of is it formatted.

To get the subtitles as string in any of the supported formats you can use
```
  var manifest = await yt.videos.closedCaptions
      .getManifest('....');
  var trackInfo = manifest.getByLanguage('en', format: ClosedCaptionFormat.srv3);
  print(yt.videos.closedCaptions.getSubTitles(trackInfo.first));

```

These are currently the available formats:

https://github.com/Hexer10/youtube_explode_dart/blob/40873f5893fde8639f55173df3e06d742b7ea947/lib/src/videos/closed_captions/closed_caption_format.dart#L8-L21

Unfortunately there is no vtt support out of the box

**Comment by zxl777** [comment]
Cool ! Thanks.

**Comment by zxl777** [comment]
Error: Undefined name 'ClosedCaptionFormat'.

```
var trackInfo = manifest.getByLanguage('en',
                      format: ClosedCaptionFormat.srv3);
```
