### ISSUE TITLE
Directly stream YouTube video to flutter video player

### ISSUE THREAD

**Issue by faslurrajah** [Hexer10/youtube_explode_dart#85]
Hi,
Is there any way to play a youtube video using [Flutter video playe](https://pub.dev/packages/video_player)r in Android API below 20 without downloading it to storage? How to generate an URL

**Comment by zxl777** [comment]
I just tested video_player 1.0.0 and it works. It can be played by directly opening the remote url of https. And this url, you can use youtube_explode_dart to get the url.

**Comment by faslurrajah** [comment]
Can you please send a sample code? how can I generate a youtube download URL ?

**Comment by faslurrajah** [comment]
There no packages available for playing youtube in Android API below 20 till now in Flutter. You can develop one with Video Player Package

**Comment by Maadhav** [comment]
Here is how to get the URL  for streaming into the video player.
```
Future<void> main() async {
  var yt = YoutubeExplode();
  var manifest = await yt.videos.streamsClient.getManifest('YA8YbmIzl_U');
  var streamInfo = manifest.muxed.withHighestBitrate();
  print('streamInfo ${streamInfo.url}');
  // Close the YoutubeExplode's http client.
  yt.close();
  exit(0);
}
```

**Comment by faslurrajah** [comment]
> Here is how to get the URL for streaming into the video player.
> 
> ```
> Future<void> main() async {
>   var yt = YoutubeExplode();
>   var manifest = await yt.videos.streamsClient.getManifest('YA8YbmIzl_U');
>   var streamInfo = manifest.muxed.withHighestBitrate();
>   print('streamInfo ${streamInfo.url}');
>   // Close the YoutubeExplode's http client.
>   yt.close();
>   exit(0);
> }
> ```
 I got this error from API 19, video_player: ^1.0.1
`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [640, 360, 29.97003], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null`)

**Comment by faslurrajah** [comment]
> Here is how to get the URL for streaming into the video player.
> 
> ```
> Future<void> main() async {
>   var yt = YoutubeExplode();
>   var manifest = await yt.videos.streamsClient.getManifest('YA8YbmIzl_U');
>   var streamInfo = manifest.muxed.withHighestBitrate();
>   print('streamInfo ${streamInfo.url}');
>   // Close the YoutubeExplode's http client.
>   yt.close();
>   exit(0);
> }
> ```

Anyway, url is working with higher api devices

**Comment by faslurrajah** [comment]
> I just tested video_player 1.0.0 and it works. It can be played by directly opening the remote url of https. And this url, you can use youtube_explode_dart to get the url.

Did you test it with API less than 20?

**Comment by zxl777** [comment]
I have not tested it.
Why do you want to test with API less than 20, the performance of these devices is already very slow.

**Comment by faslurrajah** [comment]
> I have not tested it.
> Why do you want to test with API less than 20, the performance of these devices is already very slow.

Yeah. That's right. I've been developing an educational app fro students from rural areas. These students are still using older versions of androids. So I just wanna give compatiblity for their device. But android ExoPlayer is not seems supports for avc video type.

**Comment by Hexer10** [comment]
Does this still active? Can you close if the issue is now solved?
