### ISSUE TITLE
Speed up the search and the link functions

### ISSUE THREAD

**Issue by lain-ke** [Hexer10/youtube_explode_dart#87]
**Is your feature request related to a problem? Please describe.**
First, thanks for this amazing plugin, I love it! But the thing is, when a do a search with it, let's say *Youtube rewind* the query takes about 10 seconds to complete, and to get the link 5 seconds (I'm quite happy with that).

**Describe the solution you'd like**
Since there's no need for an API key, I guess that the plugin scraps the content from the YouTube website, so I was thinking if there could be a faster way to do it, like with an external site or blocking the css/javascript scripts from loading or something...

**Describe alternatives you've considered**

- Make use of an online YouTube scrapper
- Limit what the plugins loads (blocking css/javascript etc...)
- Add a *limit* to the query

**How should this be implemented**
Again, the best solution would be to use an online YouTube scrapper.

**Additional context**
Not applicable.

**Comment by lain-ke** [comment]
Update: Here's a website I found that scraps the search result quite quickly: https://youtube-scrape.herokuapp.com/api/search?q=QUERY_HERE&page=1

**Comment by Hexer10** [comment]
It's been more than a month so I'm not sure if you are still looking into this, however I've been implementing the save api that the heroku app has been using you can see an example in the tests:
https://github.com/Hexer10/youtube_explode_dart/blob/a9275af1e20d1c784e99f9afdc0c26701f81c539/test/search_test.dart#L20-L37

Which doesn't take much time at all, feel free to comment more here if you still need help.

Note: The aim of this project is not to include any external api besides the youtube one.
