### ISSUE TITLE
[BUG] VideoUnplayableException by playerConfig == null

### ISSUE THREAD

**Issue by zxl777** [Hexer10/youtube_explode_dart#88]
videoID. "-rAeqN-Q7x4"

![image](https://user-images.githubusercontent.com/816448/100226643-fa6de400-2f5a-11eb-9a29-dfd341cc8a46.png)

**Comment by Aksi0** [comment]
I have the same error.

**Comment by Hexer10** [comment]
Should be fixed with `1.7.3` please open I new issue if this still happens.
