### ISSUE TITLE
Very Slow Download!

### ISSUE THREAD

**Issue by snookers1** [Hexer10/youtube_explode_dart#92]
1.7.3 version very slow download. 1.6.2 version was working very good. But new version very slow. Please help me.

**Comment by Artx-II** [comment]
I can confirm, I had to revert changes in youtube_http_client.dart from commit a6f2dcf

**Comment by Hexer10** [comment]
Seems like the rate limitation was needed here, I'll revert as it was before in next version

**Comment by snookers1** [comment]
> I can confirm, I had to revert changes in youtube_http_client.dart from commit [a6f2dcf](https://github.com/Hexer10/youtube_explode_dart/commit/a6f2dcf27251dab1e06a0a2b36ddb9ae8ccfb39f)

It's work for me. Thank you.

**Comment by rodrigolmacedo** [comment]
same here...

**Comment by Hexer10** [comment]
This should be fixed with the latest version `1.7.4`
