### ISSUE TITLE
Asking for advice 

### ISSUE THREAD

**Issue by Joseph-Nathan** [Hexer10/youtube_explode_dart#93]
is there any way to get facebook  video url manifest ,
or some http request that can used to help .

**Comment by Joseph-Nathan** [comment]
there is a package for android but ,I can't  under sand it 
[ youtubedl-android ](https://github.com/yausername/youtubedl-android) ,
is that possible to provide it in flutter ?

**Comment by Hexer10** [comment]
That is a wrapper around `youtubedl`  (a library written in python) which other than youtube offers a lot more providers and features, tough this is not the aim of this project. If you are able to make it work you should be able to call the java code from flutter.
