### ISSUE TITLE
➕ Add toJson and fromJson constructors to all models so it is easier to deploy on a server

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Hexer10/youtube_explode_dart#94]
Well, the idea is easy, add to each class that is a data class like video, playlist, etc a `toJson` and `fromJson` methods.

I can do a pull request 🙈.

**Comment by Hexer10** [comment]
Feel free to send a pr!

Note that the json_serializable is already installed since is being used in some part of the code, you'd just need to use the proper annotations on the other members.

Other than that why would you need this feature?

**Comment by YazeedAlKhalaf** [comment]
I am running the code on a server which returns json, woulb be way easier to have a method that searializes the classes

**Comment by YazeedAlKhalaf** [comment]
It needs a lot of code and you can just create your own objects so yea I will close it for now
