### ISSUE TITLE
400's for getting manifest on 1.7.5

### ISSUE THREAD

**Issue by anleac** [Hexer10/youtube_explode_dart#95]
Any YouTube link throws a 400 on failed request.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/13091188/104946247-05248280-59ba-11eb-88e8-051abc72fac9.png">

Tried on a variety of YouTube formats too, all returned same error and eventual timed out.

I assume YouTube made a breaking changed?

**Comment by Hexer10** [comment]
Could you send the video id which throws this error?

**Comment by anleac** [comment]
Sure! @Hexer10 the specific one I used was a pretty pointless video: https://www.youtube.com/watch?v=z9BQ4eLRXH0

**Comment by anleac** [comment]
☝️ No longer able to repro, neither on master of a fork, or within my custom app pointing at 1.7.5

Possible for YouTube to throttle certain IP's/device ID's requesting and it'd surface as a 400 also?

Either way - feel free to close this as a non-op.
