### ISSUE TITLE
Still not working with 1.7.3  ===>>>  FormatException (FormatException: Unexpected character (at character 2) {args:{raw_player_response:ytInitialPlayerResponse}}  ^ )

### ISSUE THREAD

**Issue by Nasirjavaid** [Hexer10/youtube_explode_dart#97]
Should be fixed with `1.7.3` please open a new issue if this still happens.

_Originally posted by @Hexer10 in https://github.com/Hexer10/youtube_explode_dart/issues/89#issuecomment-737160217_

**Comment by Hexer10** [comment]
Dupe of #96
