### ISSUE TITLE
➕ Add Pagination Support (if possible)

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Hexer10/youtube_explode_dart#98]
Pagination I mean in videos search, like some key to be provided in the next request which brings another batch of videos. Like if I search for kids, I get 20 results but then I want 20 more and more and more.

**Comment by Hexer10** [comment]
Please describe further what you'd like to be implemented

**Comment by Artx-II** [comment]
You can archive this pagination function by using a StreamSubscription and pausing/resuming it (for example pausing it at 10 results and then resuming it for 10 results more).

Pagination support would make this a lot easier but I don't know if that is possible.

**Comment by YazeedAlKhalaf** [comment]
It needs a lot of code and you can just create your own objects so yea I will close it for now

**Comment by Hexer10** [comment]
This was implemented for the search client in `1.8.0` playlist video do not have such videos too.

**Comment by Hexer10** [comment]
`SearchList` now does exactly this, for the playlist videos I didn't find that need since playlist usually are not thousands of videos long.

**Comment by Samriddhi-Karmacharya** [comment]
The .nextPage() method provided by the SearchList and also VidoSearchList tends to return videos that have already been fetched in the initial search api call resulting in duplicate videos in the lisitng. Is this the expected beahvaiour or am I doing something wrong?
