### ISSUE TITLE
[BUG] getHttpLiveStreamUrl returns VideoUnplayableException

### ISSUE THREAD

**Issue by murilosamuel** [Hexer10/youtube_explode_dart#99]
**Describe the bug**
When I try to use the getHttpLiveStreamUrl method, the exception "VideoUnplayableException" is returning. **(ONLY iOS)**

**To Reproduce**
Include the code which doesn't work in the code markdown..
```dart
....
YoutubeExplode yt = YoutubeExplode();
return FutureBuilder(
        future: yt.videos.streamsClient.getHttpLiveStreamUrl(VideoId('36YnV9STBqc')),
        builder: (context, snapshot) {
 ...

```

**Stacktrace**
```
Video '36YnV9STBqc' is unplayable.
Streams are not available for this video.
In most cases, this error indicates that there are some restrictions in place that prevent watching this video.
Reason: We're experiencing technical difficulties.
```

**Enviroment: (please complete the following information):**
 - Enviroment: Flutter/Dart
 - Version: 1.22.6 / 2.10.5
 - YoutubeExplode Version ^1.7.5
**Additional context**
The problem only happens on iOS. I tested with Android, and it worked perfectly.

**Comment by wackyapps** [comment]
I am facing this problem on Android also for past two days.

**Comment by Hexer10** [comment]
This should be fixed and is no longer repoducible.

**Comment by venomanse** [comment]
Hello @Hexer10 

Recently, this exception has emerged:

Exception has occurred.
VideoUnavailableException (VideoUnavailableException: Video '3L0liZFI0Z4' is unavailable
In most cases, this error indicates that the video doesn't exist, is private, or has been taken down.
If you can however open this video in your browser in incognito mode, it most likely means that YouTube changed something, which broke this library.
Please report this issue on GitHub in that case.)

Video can be opened in incognito mode in browser.

Error thrown in static Future<WatchPage> get(YoutubeHttpClient httpClient, String videoId) 
<img width="756" alt="Screenshot 2024-12-08 at 12 43 25" src="https://github.com/user-attachments/assets/3dbc455e-f170-4b00-848c-b590efebdba5">
